### ISSUE TITLE
no blue border on focused window

### ISSUE THREAD

**Issue by Z-FiRE** [B00merang-Project/Windows-10#101]
There's no blue border on focused window.

To solved it, edit metacity-1/metacity-theme-1.xml : 
60: <line color="#1883d7" x1="0" y1="0" x2="0" y2="height"
62: <line color="#1883d7" x1="0" y1="0" x2="width" y2="0"
64: <line color="#1883d7" x1="width - 1" y1="0" x2="width - 1" y2="height"
101: <rectangle color="#1883d7" x="0" y="0" width="width"
111: <rectangle color="#1883d7" x="0" y="0" width="width"
121: <rectangle color="#1883d7" x="0" y="0" width="width"

Sorry I don't have any git tools right now to do it myself :s hope someone will

**Comment by Elbullazul** [comment]
@Z-FiRE hi,

this feature is non standard as many users asked for an all-white decoration
