### ISSUE TITLE
menu selector : become large white border box from grey box

### ISSUE THREAD

**Issue by Z-FiRE** [B00merang-Project/Windows-10#104]
The selector is a grey box in Windows 10, not a transparent box with large white border.

It was this grey box in the old version of the theme...

**Comment by Elbullazul** [comment]
@Z-FiRE this issue concerns the Icong task manager, please continue conversation @ #102

**Comment by Z-FiRE** [comment]
The Menu applet is totally independant from ITM applet. What do you mean ?

**Comment by Elbullazul** [comment]
@Z-FiRE sorry, read title in a hurry.

It was supposed to mimick the live tile selection mode, however I can rollback changes if it doesn't look good enough

**Comment by Z-FiRE** [comment]
Oh ok. Here is the right style (screenshot of W10Pro latest build and patched) : 
![windows_menu](https://user-images.githubusercontent.com/17310029/27597258-2680e310-5b62-11e7-9061-2810f6c0783c.png)
Left : the effect on the menu with a rollover (grey box), and the default tile effect
Right : the rollover effect on the tile (firefox). It's effectively a white square but the opacity is not 100%

Hope it helps.

**Comment by Elbullazul** [comment]
@Z-FiRE ok, will reduce opacity on next update

thanks for the picture and the feedback

**Comment by Z-FiRE** [comment]
Damned you're fast !

**Comment by Elbullazul** [comment]
4ee845a fixes this
