### ISSUE TITLE
Cinnamon 3.4 speaker icon issue

### ISSUE THREAD

**Issue by Extarys** [B00merang-Project/Windows-10#105]
Amazing work!

I downloaded the icon set from your website along with the 1.0 windows 10 theme. (Does it also comes in black?)

I attached an image - everything is great except for the speaker icon which display an "audio file" type icon instead.
![win10](https://user-images.githubusercontent.com/11581433/27821522-91c7e642-6070-11e7-8cf7-459b5c32ed7a.png)

Also, is it possible to add a little padding in List View Mode in Nemo? The lists looks very compacted and multiple lines are quite hard to read.

<3 cheers

**Comment by Elbullazul** [comment]
@Extarys the sound icon should be a speaker. The music icon appears when a music player is open, even if it's closed. You have to click on the icon and press quit in the menu to get the speaker icon

**Comment by Extarys** [comment]
Very sorry, thank you!
