### ISSUE TITLE
Nice Theme, little issue on Mate 1.18 - OSD Volume

### ISSUE THREAD

**Issue by idontkn0w123** [B00merang-Project/Windows-10#107]
Hey,

I like your theme very much, however one little thing that bothers me is the Multimedia OSD (think it's called that way, OSD when vol up/down) in Mate 1.18. The bar is not visible, for me all is black.
Adding 

`MsdOsdWindow.background.osd .progressbar {
    background-color: @bg_color;
}`

to "gtk-3.20/gtk-contained.css" resolves that issue. In your "gtk-3.20/gtk-contained.css" at line 192 to 199 I was not able to achieve that result.

**Comment by Elbullazul** [comment]
@idontkn0w123 thanks for the report, will try and puch the fix soon

**Comment by GroumphyOriginal** [comment]
This is linked to the issue #118 too (global issue on MATE)
