### ISSUE TITLE
How to replace start menu icon?

### ISSUE THREAD

**Issue by xpirad** [B00merang-Project/Windows-10#108]
![image](https://user-images.githubusercontent.com/24430064/29203623-cdd2c34e-7ea4-11e7-9ca1-c94dabf2eb61.png)

Hi, I'm using Cinnamon 3.4.i installed the theme.But the start menu icon hasn't been replaced.It's still the linux mint icon.
Can you tell me how to do it so that it looks like the one in the picture?
Thanks.

**Comment by feren** [comment]
@xpirad Go into Right-click Menu, Configure, Panel, Custom Icon, Set path to '' (without the quotes)

**Comment by xpirad** [comment]
It worked! Thank you!!
