### ISSUE TITLE
Windows icon always appears on the first panel applet

### ISSUE THREAD

**Issue by cozylife** [B00merang-Project/Windows-10#110]
The Windows icon always appears on the first panel applet which prevents me from changing the icon on the menu, or having any applet (such as a spacer) before the start icon. Only the "Light" and "Dark" themes do that, not "Metro."

![bug](https://user-images.githubusercontent.com/8941225/30282407-372f89a2-96e3-11e7-8a86-48f87423b37b.png)

I haven't found a way to remove the windows logo yet.

**Comment by feren** [comment]
@cozylife That is by design of @Elbullazul 's, though, I do agree that it'd be nicer to be able to change the symbol in the middle of it tho

**Comment by Elbullazul** [comment]
551b55b fixes this
