### ISSUE TITLE
Missing loud speaker icon for alsa mixer aplet

### ISSUE THREAD

**Issue by krzynio8** [B00merang-Project/Windows-10#112]
Nice job!
I use the theme on XFCE/Debian. The icon with loud speaker for Alsa Mixer applet on the panel is missing. i checked it and the icon exists but when alpha is 100% then speaker icon is drawn with white pen on white color thus it is invisible. Only red cross is visible when speaker is turned off. 
Best regards Krzysztof

**Comment by Elbullazul** [comment]
@krzynio8 appreciate the feedback, but will move the issue to the appropriate repository
