### ISSUE TITLE
Changing the default font / size in gnome-shell.css

### ISSUE THREAD

**Issue by joaogma** [B00merang-Project/Windows-10#115]
I tried to change the font and size of the Shell theme without success. It simply ignores any family or size. Is it possible to do something like this with the .css?

**Comment by Elbullazul** [comment]
In theory yes, but I never tried to do so.

The whole shell theme is kind of outdated, with parts not applying anymore on gnome 3.20 and over.

I don't know when I'll get time to upgrade it
