### ISSUE TITLE
mismatch color of xfce panel

### ISSUE THREAD

**Issue by denikris** [B00merang-Project/Windows-10#116]
![screenshot_2017-10-29_20-20-39](https://user-images.githubusercontent.com/16707606/32144139-c0174826-bce6-11e7-800f-26316a1c2919.png)
xubuntu 17.04
xfce 4.12

**Comment by Elbullazul** [comment]
appears to be the same bug as #89

**Comment by ZardoZAntony** [comment]
I have this problem (only sound and net) in Mint 18.2 xfce. xfce_indicator use GTK3.0 bg_color for paint background. This is problem of plugins.

**Comment by Elbullazul** [comment]
fixed with [release 2.0](https://github.com/B00merang-Project/Windows-10/releases/tag/2.0)
