### ISSUE TITLE
Request: small widget variant for small screen

### ISSUE THREAD

**Issue by denikris** [B00merang-Project/Windows-10#117]
![screenshot_2017-10-29_20-27-35](https://user-images.githubusercontent.com/16707606/32144194-ae768e28-bce7-11e7-86e3-8dffc6ec6f7e.png)
some option not accessible because of small netbook resolution

**Comment by Elbullazul** [comment]
does it work best with another theme?

**Comment by denikris** [comment]
![adapta-eta](https://user-images.githubusercontent.com/16707606/32168962-20192338-bda1-11e7-8e7e-09f5a0009be6.png)
![greybird](https://user-images.githubusercontent.com/16707606/32168963-208c3a6c-bda1-11e7-8e25-4976d02acc62.png)

first image is adapta-eta, if i set adapta, it will look large like your theme, eta is small widget variant for linux with res smaller than 1080p
second is greybird
it's my netbook that have small screen with 1024x600, i like your work, small variant of this theme will be great :-)

**Comment by Elbullazul** [comment]
yes. I deduce you're running GTK 3.20, and we're actually reworking the theme for cross-compatibility with other of our themes, so expect changes soon...

**Comment by Elbullazul** [comment]
I think newer versions are more compact
