### ISSUE TITLE
Linux Mint 18.3 (MATE 1.18.0) not support?

### ISSUE THREAD

**Issue by emkei-cz** [B00merang-Project/Windows-10#118]
Hi,

I can not load theme Windows 10.

https://forums.linuxmint.com/viewtopic.php?f=211&t=258986

**Comment by luc2** [comment]
Same problem for me.

```
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
```

The theme installs correctly, but does not appear in `Preferences` > `Appearance`.

**Comment by bluedxca93** [comment]
Hi,
can you try to make a custom theme settings in this application.Double
click on a theme set. Then you see another window...

**Comment by Elbullazul** [comment]
@emkei-cz @luc2 I rewrote the installation guide for mate desktop. [Try this new method](https://b00merang.weebly.com/easy-installation-guide.html), I think it should work (under title **MATE desktop**)

sorry for late reply

**Comment by GroumphyOriginal** [comment]
I confirm the non support of the Mint 18.3 Sylvia with MATE Desktop. 
On your installer, with the latest Transpack, in the log file, I've the next: 
`Unknown Desktop Environment. Proceeding with Legacy installation...
metacity detected as Window manager, assuming Unknown`

That give error too on the next: 
```
Applying Windows 10 Dark to: Unknown: 
Unsupported Desktop environment: 
```

But files are copied in the right directory and with a new loading of the windows, we can view the theme. 
Also note that the "Start Menu" is not adapter too... Please find here a sample of desktop (with manual apply)
![full_desktop_menu](https://user-images.githubusercontent.com/26502547/35182524-fcfd9160-fdd6-11e7-91e7-dab6b104aa6a.png)

Also note that the error log contains another error:
`Wrong color number`

I've checked the script but all seem OK... I don't understand why...

**Comment by Elbullazul** [comment]
@groumphyoriginal mate is supported. It is only the script that's a bit outdated.

Color number is a script calling a bad function, nothing related to the theme

**Comment by JustinSpedding** [comment]
I am running Linux Mint 18.3. Both the light and dark themes are still broken with the entirely black controls as shown in the screenshot above. I tried with both Cinnamon 3.6 and MATE 1.18. I have both GTK 3.18 and 2.24 installed with the murrine theme engine. Are there any plans to fix this?

**Comment by Elbullazul** [comment]
@JustinSpedding install one theme at a time, the script is super outdated, so you have to do a manual install for themes to install properly
