### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by DanielRios549** [B00merang-Project/Windows-10#119]
Is there an way to change the colors of this theme, even if i need to compile it? I want to change the blue color to green, to match with Mint-Y theme, I use this theme only on desktop, and the colors are not updated when I change the cinnamon.css file, I think I am doing it wrong

**Comment by Elbullazul** [comment]
Some highlight use images as trending option instead of a CSS color.

Change the hover.svg and hover2.svg picture colors in the background-assets folder

**Comment by DanielRios549** [comment]
Oh my, thank you so much

**Comment by feren** [comment]
@DanielRios549 TIP: You can use `find` in combination with `sed` to change the colour code of the blue to another colour where possible in the theme, with Terminal, in one command, while changing it for every file.
