### ISSUE TITLE
Launcher isn't changing

### ISSUE THREAD

**Issue by thedonquixotic** [B00merang-Project/Windows-10#122]
I installed the theme. This is my first time installing a theme on Ubuntu or Linux. I dropped it in the folder and it still wouldn't come up on the appearance tab, so I went to the boomerang website and decided to use the Unity Tweaker Tool to change the theme. That worked, but it didn't work for actual launcher bar. 

Also main thing I'm just trying to do is get rid of all the extra crap on the launcher bar, and expand out the labels. I don't like having only icons to go off of and having to cycle through different windows of the app. I just refer good old fashioned taskbar. I know that's not normal for linux but I've seen some stuff that seems like it should be possible on Ubuntu but I can't figure out how.

**Comment by Elbullazul** [comment]
you're searching for something like [taskbar for gnome](https://extensions.gnome.org/extension/584/taskbar/) or [dash to panel](https://extensions.gnome.org/extension/1160/dash-to-panel/)

if not, you could install the cinnamon desktop: ![cinnamon-desktop](https://spins.fedoraproject.org/static/images/screenshots/screenshot-cinnamon.jpg)

**Comment by thedonquixotic** [comment]
And this will work with Ubuntu 16? Because that still uses the Unity Launcher
doesn't it?  








On Mon, Mar 19, 2018 8:39 AM, Christian Medel notifications@github.com  wrote:
you're searching for something like taskbar for gnome  or dash to panel

if not, you could install the cinnamon desktop:

**Comment by Elbullazul** [comment]
this won't work for unity. You could try something like hiding the launcher and installing xfce4-panel or tint2

**Comment by thedonquixotic** [comment]
Cool. I've looked into it and it seems I'll need to install the gnome shell.
This won't effect compatibility with any programs will it? I'm an
artist/designer and I'm installing some neural networks for a project I'm
working on, but they have limited compatibility with versions of Ubuntu.
Installing gnome shell won't effect the actual OS though correct?







On Mon, Mar 19, 2018 12:48 PM, Christian Medel notifications@github.com  wrote:
this won't work for unity. You could try something like hiding the launcher and
installing xfce4-panel or tint2

**Comment by Elbullazul** [comment]
it wouldn't in theory, although unity and gnome will probably interfere on core files and you could crash your display server.

I'd recommend you first try xfce4-panel and see if it meets your needs, since there's no risk of unity crashing because of it

**Comment by thedonquixotic** [comment]
Sure thing, thanks. I'll check that out. Also just to make sure I'm
understanding correctly, that basically means that I'm installing the XFCE shell
on Ubuntu correct?


Sincerely,David Aslan French  
Jackalope.tech Design X Code: Pushing the boundaries of design, art, and code.
 jackalope.tech  
Find me on Facebook  Let's connect!  








On Mon, Mar 19, 2018 12:52 PM, Christian Medel notifications@github.com  wrote:
it wouldn't in theory, although unity and gnome will probably interfere on core
files and you could crash your display server.

I'd recommend you first try xfce4-panel and see if it meets your needs, since
there's no risk of unity crashing because of it

**Comment by Elbullazul** [comment]
no, only the panel:

![xfce4-panel](http://1.bp.blogspot.com/-VV0YOGsxhvg/Ve7OwbeG7BI/AAAAAAAAW28/UkGGw4Kp0nI/s1600/xfce4-dockbarx-plugin.png)

**Comment by Elbullazul** [comment]
no, only the panel:

![xfce4-panel](http://1.bp.blogspot.com/-VV0YOGsxhvg/Ve7OwbeG7BI/AAAAAAAAW28/UkGGw4Kp0nI/s1600/xfce4-dockbarx-plugin.png)

of course, you could install the complete xfce4 desktop, and that would be less of a hastle than just installing a single part of it

**Comment by thedonquixotic** [comment]
Okay cool. I will try that. Thanks!  








On Mon, Mar 19, 2018 1:41 PM, Christian Medel notifications@github.com  wrote:
no, only the panel:



of course, you could install the complete xfce4 desktop, and that would be less
of a hastle than just installing a single part of it
