### ISSUE TITLE
Please support Windows OS

### ISSUE THREAD

**Issue by ashaduri** [B00merang-Project/Windows-10#123]
The official "Windows" theme in GTK+ is in a sorry state. Titlebars don't look as they should (with client-side decorations), widgets look off (and are functionally broken in Windows 7 Classic), etc...
Nobody seems interested in fixing it. But they will accept patches.

Is it possible to port this theme it Windows? I guess the main difference is the titlebar and the adoption of colors from Windows color scheme (GTK+ has the ability to retrieve these colors in CSS, which the official theme does).

Thanks!

**Comment by Elbullazul** [comment]
are you asking for a port to Microsoft Windows or to some other distro using GTK 2?

**Comment by ashaduri** [comment]
I'm asking for a port to Microsoft Windows, so that this theme can be used instead of the GTK+3-bundled "MS-Windows" theme.

This project came up in the discussion about the ugliness of GTK+3/4 in the Windows platform. See comments at:
https://gitlab.gnome.org/GNOME/gtk/issues/105

Thanks

**Comment by Elbullazul** [comment]
if I get it right, you wish for this theme to run well on GTK+ for the MS Windows platform? That would be interesting, although I have no experience with that framework.

where do I download that framework and how do I use it?
