### ISSUE TITLE
Disabled State mixed with Enabled State

### ISSUE THREAD

**Issue by feren** [B00merang-Project/Windows-10#127]
Simple as that, the issue is that disabled buttons look enabled, and enabled buttons look disabled, in both Light and Dark Themes. GTK 3.20.

**Comment by feren** [comment]
![screenshot from 2018-05-19 22-11-33](https://user-images.githubusercontent.com/11057934/40273084-9c895268-5bb1-11e8-8ba1-2f7e1fe6b58d.png)

**Comment by feren** [comment]
...assigned you since you have the compilation script for the theme, or however you make the GTK 3.20 theme, and I don't...

**Comment by Elbullazul** [comment]
I'm guessing it's Xed in the screenshot? If you want you can submit a PR before I tackle this issue. The compilation project as been abandoned for some time now.

**Comment by feren** [comment]
Xed, yeah

**Comment by feren** [comment]
It also affects Chrome OS (I think), macOS and macOS Dark GTK Themes...

**Comment by Elbullazul** [comment]
Does it happen with this one?

https://github.com/Elbullazul/B00merang-Flat

**Comment by Elbullazul** [comment]
Does this only affect icons or controls?

**Comment by feren** [comment]
Only All Controls with a disabled state, oh and icons in GTK Button Option Dialogs (e.g.: Save? Dialog)

**Comment by Elbullazul** [comment]
is the text affected or only the icons?

**Comment by Elbullazul** [comment]
and does it happen with the B00merang Flat theme?

**Comment by feren** [comment]
Text is also affected (looking in menus)

**Comment by feren** [comment]
For B00merang Flat... I dunno, really hard to differentiate enabled and disabled for me.
![screenshot from 2018-07-24 17-13-03](https://user-images.githubusercontent.com/11057934/43151936-00200bfa-8f65-11e8-8bdb-d441aab9e4e5.png)

**Comment by Elbullazul** [comment]
fixed with [release 2.0](https://github.com/B00merang-Project/Windows-10/releases/tag/2.0)
