### ISSUE TITLE
Unable to install on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by vojtechsmejkal** [B00merang-Project/Windows-10#129]
I've been trying to install this theme on fresh installation of Ubuntu 18.04 but no luck so far. If anyone managed to get it working, I would be really glad for any advice. Thanks.

**What I've done**
1. Installed gnome-tweak-tool and gnome-shell-extensions
2. Rebooted PC, went to Tweaks app and enabled _User themes_
3. Downloaded installer script and executed it

**What happens**
Installer runs normally but then this message appears: 

> The user themes extension must be enabled to apply the windows 10 shell theme

and I get redirected to this url: https://extensions.gnome.org/extension/19/user-themes/, but even there it says I have this extension enabled. I close browser window and script ends with this error:

> Something went wrong while installing: GTK theme. Aborting...: 

thats it. Some things chane like windows style, some icons, top bar gets dark ... but obviously many things are missing. Mainly taskbar is untouched.

**Installer script, terminal & log**
[install.log](https://github.com/B00merang-Project/Windows-10/files/2081635/install.log)
[terminal.txt](https://github.com/B00merang-Project/Windows-10/files/2081636/terminal.txt)
[windows10.sh.txt](https://github.com/B00merang-Project/Windows-10/files/2081641/windows10.sh.txt)

Any suggestion is welcomed. If going back to older version of Ubuntu helps, please let me know.

**Comment by Elbullazul** [comment]
The install script is deprecated. Manual installation is required. In gnome tweak, change the gtk, icon and shell themea to windows 10.

I'll remove the install script in short

**Comment by HenrikBach1** [comment]
Hi,

I'm not able to use the install script, due to it fails. I've left the details, due to your install script is deprecated and will be removed.

However, I'm not a big fan for doing manual customizations, so then you loose me...

/Henrik

**Comment by r2binx** [comment]
Unfortunately gnome tweaks doesnt show your theme. Can you elaborate where I need to extract in order to make it work?

**Comment by Elbullazul** [comment]
@r2binx you have two choices:
1) dash to dock (macOS-style) : https://extensions.gnome.org/extension/307/dash-to-dock/
2) dash to panel (Windows-style) : https://extensions.gnome.org/extension/1160/dash-to-panel/
