### ISSUE TITLE
Enabled states still look disabled and Disabled enabled

### ISSUE THREAD

**Issue by feren** [B00merang-Project/Windows-10#130]
Like the title says, on pretty much ALL of the B00merang Theme's I've tested with, MOST of the enabled states look like their disabled counterparts, while the disabled states look like their enabled counterparts... Basically, they're flipped on your themes, not just the Windows-like ones, either.

**Comment by Elbullazul** [comment]
you can just bump #127 next time

I'm planning on reworking this, but not much time yet.

also, is it just exclusive on Mint apps?
