### ISSUE TITLE
where is the appearance manager?

### ISSUE THREAD

**Issue by zzzgit** [B00merang-Project/Windows-10#133]
`5. You're all set! Open your appearance manager and select the corresponding themes from the list`

but where is the appearance manager?

**Comment by Elbullazul** [comment]
What distro do you use, and which desktop environment is installed?

**Comment by zzzgit** [comment]
arch Linux with gnome

**Comment by Elbullazul** [comment]
Neither arch or gnome have a pre-installed app for that. You need to install gnome-tweaks
