### ISSUE TITLE
bug panel xfce:xubuntu,mint 18.3/19,zorin lite,Manjaro

### ISSUE THREAD

**Issue by anim4k** [B00merang-Project/Windows-10#134]
Hello i installing "Windows theme 10" in mint xfce devices my friends 
because many my friends use windows 10 They don t know how to use Linux -   theme is great  but there is a problem in the panal color I hope to fix it sorry my english :) 
https://serving.photos.photobox.com/255205815206c0de92627df309d4d4ff38d773ac05381bf1c5425297cdc0612d19a0d79f.jpg
:+1:

**Comment by Elbullazul** [comment]
try this version:

https://github.com/B00merang-Project/Windows-10/archive/xfce.zip

**Comment by anim4k** [comment]
sorry sir same probleme https://serving.photos.photobox.com/75588409c5b918dab1cfd6cc6adcdf311efb76f5501503b709564c5ee13b304f9f639815.jpg
:(

**Comment by Elbullazul** [comment]
retry it, I pushed some fixes

**Comment by anim4k** [comment]
Unfortunately the same problem 
i try other theme like arc or Adapta working fine only this theme have some mistakes.

**Comment by anim4k** [comment]
I have a note sir (Windows10 theme dark) in xfce panal working good look
https://serving.photos.photobox.com/50230728c285283c5a6e74b698fbe2182bfd6ab812efec2fc4fbb6b1c539b30f364affd6.jpg

**Comment by Elbullazul** [comment]
dark theme turns everything dark, so it's not particularly better at coloring the panel ;)

right now I'm a bit busy with another theme, but once that's finished I plan to port this theme to the cleaner codebase, so I don't get this kind of issues anymore.

meanwhile you can override the theme colors with right clicking the panel > customize > use custom color

**Comment by Elbullazul** [comment]
fixed with [release 2.0](https://github.com/B00merang-Project/Windows-10/releases/tag/2.0)
