### ISSUE TITLE
GTK2 has wrong colors in inkscape

### ISSUE THREAD

**Issue by elswerky** [B00merang-Project/Windows-10#137]
the latest windows 10 theme i think it needs some optimization 
as when i use it in some apps like inscape 
i see more black in them theme although i use light theme 

also i think it needs some optimization for chrome 

![deepinscreenshot_select-area_20181113085913](https://user-images.githubusercontent.com/26687459/48396304-98026c00-e722-11e8-8380-621a18cf2016.png)
![deepinscreenshot_select-area_20181113085933](https://user-images.githubusercontent.com/26687459/48396305-989b0280-e722-11e8-8d45-607f74392a1e.png)

**Comment by Elbullazul** [comment]
that looks pretty bad, will look into it

**Comment by elswerky** [comment]
Just to complete the bug report

This is on deepin desktop

Tge screenshots is from deepin desktop on manjaro (manjaro deepin)

- Also chrome theme needs much optimization

- the dark theme is darker than I think 😂😂
If i choose dark theme everything turn dark and black 
You may make dark theme with two styles (either dark theme for everything (the current present one) or just dark theme for topbar of apps

Many other themes have this option like Mac os theme there is shadow theme and dark theme and both are dark 

I am currently not opening pc so I can't send some screenshot to explain what i want to say
