### ISSUE TITLE
Update for cinnamon 4.x

### ISSUE THREAD

**Issue by ImpWarfare** [B00merang-Project/Windows-10#138]
Please update this theme for Cinnamon 4.0 which was released awhile ago.

**Comment by Elbullazul** [comment]
@Skynet100Gaming what is broken and how? post screenshots to illustrate the issues.

**Comment by feren** [comment]
Grouped Window List, primarily.

**Comment by feren** [comment]
@comnuoc Wanna Pull Request?

**Comment by comnuoc** [comment]
@feren Need to add more classes for 'Grouped Window List' applet, but I don't have time yet. I hope another one can create a complete pull request.

**Comment by Elbullazul** [comment]
Migration completed
