### ISSUE TITLE
Gnome Shell: match Windows 10 default color scheme

### ISSUE THREAD

**Issue by hlechner** [B00merang-Project/Windows-10#141]
The windows-10-master gnome shell theme uses a different blue color than windows 10 default scheme.

Screenshot from Windows 10 (1803):
![image](https://user-images.githubusercontent.com/11244067/49635322-7e350b80-f9e6-11e8-972d-749b255140c6.png)

This blue is: ``#6db8f2``

The windows-10-master gnome shell theme uses a different blue color instead: 
``rgba(53,156,196,0.95)``

the code: 

```
/* Active App underline */
.app-well-app-running-dot {
	box-shadow: inset 0 -2px 0 0 transparent;
	width: 35px;
	height: 3px;
	background-color: rgba(53,156,196,0.95);
	margin-bottom: 2px;
}
```

Since the Windows 10 do not change this bar color based on background/panel color. it can be used a solid color instead of the alpha one.

Could be used:
``background-color: #6db8f2;``
or:
``background-color: rgba(109, 184, 242, 1);``

**Comment by Elbullazul** [comment]
fixed with  baf7da7
