### ISSUE TITLE
Gnome Shell: panel background color

### ISSUE THREAD

**Issue by hlechner** [B00merang-Project/Windows-10#142]
I have checked the panel background color are a bit different and darker from what windows does have.

I have take many screenshots to compare, and I summarize with this results here:
![image](https://user-images.githubusercontent.com/11244067/49645659-ef36ec00-fa03-11e8-8e90-2bbf0e466eb3.png)
Right now the panel background uses: rgba (0, 0, 0, 0.9) as you can see it is very different from "windows 10", The closest that I could get to the windows version is: rgba(10, 10, 10, 0.8) as you can see on the imagem above is a lot closer to the windows 10 behavior.

```
/* TOP BAR (panel)*/
#panel {
	font-weight: normal;
	color: white;
	height: 32px;
	background-color: rgba(0, 0, 0, 0.9);
	text-shadow: 0 0 4px 0 transparent;
}
```
To change it, just change from ``rgba(0, 0, 0, 0.9);`` to ``rgba(10, 10, 10, 0.8);``

**Comment by Elbullazul** [comment]
fixed with baf7da7
