### ISSUE TITLE
Fonts are not arranged Linux Mint 19.1 xfce

### ISSUE THREAD

**Issue by ramzydoni** [B00merang-Project/Windows-10#146]
thank's devloper for new update theme xfce 
i try new theme today in my linux mint xfce 19.1 have a note that the distribution lines are unordered and unclear and I hope to solve this problem
https://i.imgur.com/3p1Qmsz.png

**Comment by Elbullazul** [comment]
I'll check that out, a fix should come in short time.

**Comment by Elbullazul** [comment]
e7f57be6edd24d13eb514263127bf00cef11c8e2, 4b169a3e668fcb5dc9a5ab75e92ad41f8d1c12f0 and 50105a002755d23fd06157bb06289df9c9bf916e fix this issue:

![image](https://user-images.githubusercontent.com/15310985/52170682-d5243c00-271c-11e9-9c64-a87c8084bed6.png)

my setup wasn't up to date, sorry for that
