### ISSUE TITLE
color still not match in both dark and light variant of xfce4-panel

### ISSUE THREAD

**Issue by denikris** [B00merang-Project/Windows-10#147]
xfce4-panel version: 4.12.2
xubuntu 18.04.1
missmatch plugins: clock plugin, show desktop plugin
![xfce-panel](https://user-images.githubusercontent.com/16707606/52158305-8bf6cc80-26c9-11e9-9398-9752d4684de3.png)

**Comment by Elbullazul** [comment]
I'll see what can be done about this.

**Comment by Elbullazul** [comment]
f9e69f8 should fix this, can you confirm?
