### ISSUE TITLE
Mint 19.1 Cinnamon: Window Titlebar cannot be hidden

### ISSUE THREAD

**Issue by stsichler** [B00merang-Project/Windows-10#149]
On Mint 19.1 Cinnamon, when Windows 10 themed borders are active, the Window Titlebar cannot be hidden anymore by software that tries to do this, like Firefox Web Browser (when "System Titlebar" checkbox in "Customize..." Tab is de-selected).
Also some Wine applications that try to decorate their application window by its own are unable to hide the Window Title Bar, resulting in double Title Bars.
In contrast, this works flawlessly with original Mint-X or Mint-Y border themes.

**Comment by Elbullazul** [comment]
can you post a screenshot of this?

**Comment by stsichler** [comment]
here are the screenshots of Firefox in maximized mode with "System Titlebar" option disabled:
![firefox-windows-10](https://user-images.githubusercontent.com/6442267/52975027-0ad74f00-33c4-11e9-8923-66158e87cd6b.png)
![firefox-mint-y](https://user-images.githubusercontent.com/6442267/52975030-0e6ad600-33c4-11e9-8280-3fe26cad33a0.png)

**Comment by Elbullazul** [comment]
that's interesting. Will test

**Comment by stsichler** [comment]
Hey, 
thank you! You seem to have fixed it.
But instead, there is now a theme parsing error:
(firefox:31884): Gtk-WARNING **: 11:23:25.725: Theme parsing error: <data>:1:28: Expected ')' in color definition
(firefox:31884): Gtk-WARNING **: 11:23:25.725: Theme parsing error: <data>:1:72: Expected ')' in color definition

Btw, in thunderbird, I now have a gray title bar, instead of white.

**Comment by Elbullazul** [comment]
interesting, I'll have a look

**Comment by Elbullazul** [comment]
69519e7 fixes the titlebar issue. How did you get that firefox warning?

**Comment by stsichler** [comment]
Thank you, gray titlebar is fixed! :)

The theme parsing error is reported when starting Firefox from the command line.
Hm, I'm not sure, but it may be possible that the parsing error is actually somewhere in Firefox' color theme, not in your theme. I'm up-to-date with all Firefox updates, installed version is 65.0.1+linuxmint1+tessa and I'm using the default theme.

`(firefox:6722): Gtk-WARNING **: 14:51:33.288: Theme parsing error: <data>:1:28: Expected ')' in color definition`
`(firefox:6722): Gtk-WARNING **: 14:51:33.289: Theme parsing error: <data>:1:72: Expected ')' in color definition`

**Comment by stsichler** [comment]
Oh yes, forget about this. 
It is Firefox-specific. That theme parsing error is also reported when your Theme is not active.
So IMO, this issue is fixed!
