### ISSUE TITLE
Minor issue: Theme parsing error: gtk-widgets.css:2463:47: (release 2.0.1)

### ISSUE THREAD

**Issue by stsichler** [B00merang-Project/Windows-10#150]
Theme parsing error: gtk-widgets.css:2463:47: 'theme_selected_bg_color' is not a valid color name.
In release 2.0.1, /usr/share/themes/Windows-10-2.0.1/gtk-3.20/gtk-widgets.css, line 2463, a '@' is missing.

**Comment by Elbullazul** [comment]
This is fixed in the master branch. I have some small modifs to make before making a new release
