### ISSUE TITLE
File renaming using Caja file manager is messed up

### ISSUE THREAD

**Issue by sandeep-khanna** [B00merang-Project/Windows-10#154]
Using the Windows Light/Dark them, renaming a file displays the filename all scrambled up!

Perhaps a gtk-2.0 theme issue?

The environment is a VirtualBox virtual machine running Ubuntu MATE 18.04

**Comment by leogx9r** [comment]
@Elbullazul Seems this issue might be fixed easily by pulling your fix from https://github.com/B00merang-Project/Windows-10-Dark/commit/24860ae2767cd6ded219dbaa93ffed67b05cf31b as well.

**Comment by Elbullazul** [comment]
yes, it was fixed
