### ISSUE TITLE
Install script broken?

### ISSUE THREAD

**Issue by gshaw0** [B00merang-Project/Windows-10#156]
Trying to install the theme using the transpack.sh script from https://b00merang.weebly.com/windows-10-transformation-pack-tutorial.html but it seems to be broken?

The following files fail to download (404 error if pasting path into browser manually from the script)

Windows-10-Metro
Windows-10-Icons

Leads to script Aborted \ something went wrong installing icons during the install

(attempting to install on Ubuntu MATE 16.04)

**Comment by Elbullazul** [comment]
it is, I will remove that link shortly. you can use https://raw.githubusercontent.com/B00merang-Project/Shell-Scripts/29e5ef9ee2ff6b65a789e6092fef76087dffe30c/auto_install.sh meanwhile

**Comment by Elbullazul** [comment]
also Windows 10 Metro is now [Windows 10 Acrylic Dark](https://github.com/B00merang-Project/Windows-10-Acrylic-Dark) and Windows 10 Icons [are here](https://github.com/B00merang-Artwork/Windows-10)

**Comment by tcreek** [comment]
Where are the icons suppose to be placed?

**Comment by Elbullazul** [comment]
~/.icons
