### ISSUE TITLE
All Apps Search Text Color

### ISSUE THREAD

**Issue by Draco18s** [B00merang-Project/Windows-10#157]
The text color in the search bar is white on a background of white (top center):

![image](https://user-images.githubusercontent.com/1750680/59236520-286f3500-8bbc-11e9-9d86-75c0f92e5cbe.png)

I'm not sure what tweaked this or how to fix it (I also don't get the Win10 style start menu show in the readme's screenshots for whatever reason; preferably would like to have that, but the text color seems like a bug).

**Comment by Elbullazul** [comment]
what distro and gnome version are you using?

**Comment by Draco18s** [comment]
Sorry about that.
Gnome is 3+, I'll have to check the exact version after work, but I did check it yesterday and saw that it was 3.2 or something close to that. Distro is [Pop!](https://system76.com/pop), which is an Ubuntu variant.

**Comment by Elbullazul** [comment]
is this still happening? I can't reproduce it in 20.04

**Comment by Draco18s** [comment]
Sorry I didn't get back to you right away; for WFH reasons I was booted into Windows and didn't get an opportunity to switch over until now.
Issue has gone away though!
![image](https://user-images.githubusercontent.com/1750680/100399740-8a726300-3019-11eb-9abf-ce8c774c9f4e.png)
