### ISSUE TITLE
Align metacity title to left

### ISSUE THREAD

**Issue by Arnaz87** [B00merang-Project/Windows-10#158]
Windows 10 has the title left aligned, and the font is not bold.

**Comment by leogx9r** [comment]
The title font in Cinnamon can be changed in Font Settings FYI.


![image](https://user-images.githubusercontent.com/40126089/61176186-d602a900-a5ab-11e9-883b-2689c8032426.png)

**Comment by Elbullazul** [comment]
positioning is indeed wrong. Will fix

**Comment by Elbullazul** [comment]
Implemented
