### ISSUE TITLE
workspace switcher text color 

### ISSUE THREAD

**Issue by thekomer** [B00merang-Project/Windows-10#160]
Hey! Now that you're here... here's one more issue for you :-)
Again in my xfce 4.12.3.  Selected workspace has wrong background/text color.  Number is not visible.
![workspace-switcher](https://user-images.githubusercontent.com/17909481/61244692-1187a980-a74b-11e9-9676-9da61628b817.png)
Can you change text in selected workspace to black? Or maybe you have some other solution... Workaropund would be for me to use "show miniature view" in Workspace switcher settings. But I prefer to see just name.

**Comment by Elbullazul** [comment]
I'll have a look

**Comment by thekomer** [comment]
New issue related to this one:
xfce4.12 -> desktop switcher text, for active desktop, is not visible because of too light blue background (as in screenshot from jul 25th): 
xfce4.14 -> same switcher; No difference between active and inactive desktop names.

xfce4.14:
![Screenshot](https://user-images.githubusercontent.com/17909481/67697578-11818180-f9a9-11e9-9f61-fae2560690f0.png)

**Comment by Elbullazul** [comment]
2beb30d fixes it, sorry for the long delay
