### ISSUE TITLE
Massive White search box on default cinnamon menu

### ISSUE THREAD

**Issue by ImpWarfare** [B00merang-Project/Windows-10#164]
With the Windows 10 Light theme and the latest cinnamon version it reveals a very large white search box on the top of the default main menu on cinnamon on the Arch Linux system and the white colour goes straight to the edge of the main menu and it to me doesn't look correct. Is there a reason why it changes the search bar to an ugly looking search bar on the main menu or is this a bug? I believe it shows it as well on Linux mint the last time I used it with the default start menu.

**Comment by Elbullazul** [comment]
Can you post a screenshot of the problem?
