### ISSUE TITLE
GnoMenu not looking as it should

### ISSUE THREAD

**Issue by siferati** [B00merang-Project/Windows-10#167]
How can I change the color of GnoMenu? I ran the [GNOME Layout Manager](https://github.com/vmavromatis/gnome-layout-manager) script, but for some reason the menu is gray instead of black - which looks awful.

How it should look like: ![suggested](https://i.imgur.com/0Dk4HOu.png)

How it looks: ![current](https://i.imgur.com/B3Jvhaj.png)

How can I fix this?

**Comment by Elbullazul** [comment]
What distro are you running?

GnoMenu isn't currently supported but if it turns out it's easy I can add it

**Comment by tirafesi** [comment]
I'm on Ubuntu 18.04.3 LTS.

The image shown in the ReadMe of this project is using GnoMenu right? I want to have my desktop look like the one in that image.

**Comment by Elbullazul** [comment]
yes, it's gnoMenu but an older version. We also made some changes to the theme since then, hence why it looks different

**Comment by Elbullazul** [comment]
Note to self: [this](https://github.com/The-Panacea-Projects/Gnomenu/blob/44700a14fc6042168c50cf1ac46b46fd6e758e62/extension.js#L175) could be useful in creating gnoMenu-specific style rules

**Comment by Elbullazul** [comment]
Shell themes are currently broken and will have to be redone from scratch, so this issue isn't valid anymore
