### ISSUE TITLE
Desktop icon text not visible

### ISSUE THREAD

**Issue by thekomer** [B00merang-Project/Windows-10#168]
xfce4.12 -> everything normal. 
xfce4.14 -> can't see text under desktop icons (i.e. Trash). Black wallpaper. See screenshot.

xfce4.12
![Sc](https://user-images.githubusercontent.com/17909481/67696524-573d4a80-f9a7-11e9-94bb-bf3ed72d16f0.png)

Xfce4.14:
![Screenshot](https://user-images.githubusercontent.com/17909481/67696075-80111000-f9a6-11e9-9403-80addc41474f.png)

**Comment by Elbullazul** [comment]
what distro are you using? It looks like manjaro, which unfortunately doesn't seem to play nice with my system

**Comment by thekomer** [comment]
MX Linux.
xfce4.12  <-  MX Linux 18, based on Debian 9
xfce4.14  <-  MX Linux 19, based on Debian 10

**Comment by thekomer** [comment]
:-o Sorry about the typo. :)

BTW, here are more information that you might find useful. GTK versions used by my system:
```
$ dpkg -l libgtk2.0-0 libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version      Architecture Description
+++-=================-============-============-=====================================
ii  libgtk-3-0:amd64  3.24.5-1     amd64        GTK+ graphical user interface library
ii  libgtk2.0-0:amd64 2.24.32-3    amd64        GTK+ graphical user interface library
```

**Comment by Elbullazul** [comment]
Apparently Xfce 4.14 upgrades Xfdesktop to GTK3, but in this theme still has the rules in gtkrc.

I'll migrate based on [greybird's implementation](https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/gtk-contained.css#L4686)

**Comment by thekomer** [comment]
Yeah! The whole point of Xfce4.14 was migration from GTK 2 to GTK 3. 

Xfce version 4.16, that's due in 6 months, will apparently deprecate gtk2 packages whatsoever. (I've read that somewhere)

Thank you.

**Comment by Elbullazul** [comment]
so I gave it a try, it looks like it still uses some GTK2 rules, and because the GTK2 theme is a big mess right now I can't find what causes the black text.

I think I might need to move over to a pixbuf-based GTK2 theme for this to fix.

Sorry for not being able to fix it quickly enough

**Comment by Elbullazul** [comment]
Had a new look yesterday, definetely not a GTK2 problem. At least that's one less rework to do. But I couldn't identify what caused the black text since similar themes didn't have that problem.

I'll have a deeper look tomorrow

**Comment by thekomer** [comment]
Thank you.

**Comment by Elbullazul** [comment]
Maybe it's because my version of MX isn't up to date, but it appears that the desktop icons load the globally defined variable `@theme_selected_bg_color` in gtk.css

As a temporary fix I suggest you edit the following line in gtk.css:

line 2856, from
```css
@define-color theme_selected_fg_color #000000;
```
to
```css
@define-color theme_selected_fg_color #ffffff;
```

I'll look in more detail once I have more time

**Comment by Elbullazul** [comment]
found a fix, coming soon

**Comment by Elbullazul** [comment]
should be fixed
