### ISSUE TITLE
How to get show apps icon on the dock of Dash to Dock ?

### ISSUE THREAD

**Issue by Tuxman2** [B00merang-Project/Windows-10#169]
Hi,

can you tell me how to get the show apps icon on the dock of Dash to Dock with your theme ?
It appears on the task bar (activities) but not on the dock.

Thanks.

Note: I'm using Manjaro.

**Comment by Elbullazul** [comment]
sorry, I don't understand what you mean. You want to have the "show apps" button on the Dash to Panel taskbar?

**Comment by Tuxman2** [comment]
Hi,

With your theme, the "show apps" button (the grid button) appears invisible on the dock of Dash to Dock extension. On the task bar, it appears correctly. I also want to modify the grid button by another one with your theme.

**Comment by Tuxman2** [comment]
Hi,

here is a picture of my dock using your windows 10 shell theme. The grid icon doesn't appear (look my red arrow).

Regards.

![dock](https://user-images.githubusercontent.com/23556606/73259980-dae21f80-41c0-11ea-8ed4-9e1db898c264.png)

**Comment by Elbullazul** [comment]
right, I'll fix it during the week

**Comment by Elbullazul** [comment]
As for the manjaro Icon, if I remember correctly dash to dock has a setting to change the icon, but I'm not shure

**Comment by Tuxman2** [comment]
Thanks to fix it, because there is a bug (I checked it again).
Perhaps you could add an entry in the gnome-shell.css of your themes to be able to change the grid icon like this:

`.show-apps .overview-icon {
  background-image: url("assets/nameoftheshowappsicon.png") !important;
  background-size: contain;
  /* You are Using System default ? need 6px padding for fixed icon pozition */
  padding: auto 6px;
}`

or something similar.

Regards.

**Comment by Elbullazul** [comment]
I'd rather not have something like that implemented directly to avoid CSS errors.

**Comment by Tuxman2** [comment]
I will switch from the 'dash to dock' extension to 'dash to panel' extension. But is there another solution to change the grid icon by an other icon (example: the distribution icon) if one day I want to come back to 'Dash to dock' extension ?

**Comment by Elbullazul** [comment]
I think there's a setting for that now
