### ISSUE TITLE
The Gnome tweak tool titlebar is transparent under your theme.

### ISSUE THREAD

**Issue by Tuxman2** [B00merang-Project/Windows-10#170]
Hi,

The Gnome tweak tool titlebar is transparent under your theme. How to avoid that issue ?

Thanks.

Note: I'm using Manjaro.

**Comment by Elbullazul** [comment]
What GNOME version do you have installed? Can you also include a screenshot of the issue? Thanks,

**Comment by Tuxman2** [comment]
Gnome 3.34.x.

**Comment by Elbullazul** [comment]
Can you provide a screenshot of the issue? I'm rather busy and don't have time to test it myself at the moment

**Comment by Tuxman2** [comment]
OK, I will do it as soon as possible.

**Comment by Tuxman2** [comment]
Hi,

here is the picture

![screeshottweaktool](https://user-images.githubusercontent.com/23556606/73543893-dff8d600-442f-11ea-984e-712d18a78d29.png)

As you can see the titlebar is transparent (you can see the backgroud behind) when Gnome Tweak tool is launched.

**Comment by Elbullazul** [comment]
Does it only happen with tweak tool?

**Comment by Tuxman2** [comment]
> Does it only happen with tweak tool?

I didn't see this kind of problem with the others windows (settings window, browser, file manager, ...). So, I think that it only happen with tweak tool.

**Comment by Elbullazul** [comment]
We had an override made specifically for tweak tool because their titlebar was different than most apps. I'll try to fix it by Monday

**Comment by Tuxman2** [comment]
OK. Thanks to fix it. ;-)
