### ISSUE TITLE
the icon can not work

### ISSUE THREAD

**Issue by Freed-Wu** [B00merang-Project/Windows-10#172]
![2020-02-11 22-17-09屏幕截图](https://user-images.githubusercontent.com/32936898/74244423-58a73e80-4d1c-11ea-8f7e-962167e91af5.png)

Gnome-shell: 3.3.2

the themes can work normally. but icon cannot. i had tryed many times. but i failed.

Thank you!

**Comment by Freed-Wu** [comment]
I try to change language to English but it is not useful:(

**Comment by Elbullazul** [comment]
you are using Adwaita icons. For the icon theme, you need to download https://github.com/B00merang-Artwork/Windows-10 to ~/.icons
