### ISSUE TITLE
Can the blank strips be elimitated?

### ISSUE THREAD

**Issue by Freed-Wu** [B00merang-Project/Windows-10#173]
in windows OS 10,
![Image 2](https://user-images.githubusercontent.com/32936898/74623380-5eb77800-517f-11ea-91db-bedaeee8cabd.png)

in gnome-theme windows-10, there exist two blank strips above and below icons.
![2020-02-17 12-09-19 的屏幕截图](https://user-images.githubusercontent.com/32936898/74623415-8575ae80-517f-11ea-9325-a214b4ec3139.png)

it is an enhancement. Thank you!

**Comment by Elbullazul** [comment]
@Freed-Wu interesting, had not realized there was so much wasted space. I'll get back to you when I implement a correction

**Comment by Elbullazul** [comment]
gnome's headerbar requires padding to avoid clumped up buttons. If I change some other stuff like margins, then I mess up any app that isn't a gnome app. Sorry, it can't be done without some possibly theme-breaking hacks
