### ISSUE TITLE
Controls missing in HiDPI 

### ISSUE THREAD

**Issue by Vico999** [B00merang-Project/Windows-10#178]
When the screen is scaled due to a high resolution and HiDPI is enabled, the controls are missing everywhere (the check box's and radio buttons).

OS: Kali MATE
Resolution: 3840 x 2400
HiDPI enabled

Using GTK.

Missing checkbox's
![Screenshot at 2020-04-13 11-29-07](https://user-images.githubusercontent.com/50190252/79085288-56447d80-7d7b-11ea-9531-b266fedbbdfb.png)

It should look like this (using another theme):
![Screenshot at 2020-04-13 11-29-31](https://user-images.githubusercontent.com/50190252/79085302-68262080-7d7b-11ea-9ade-c9b0f01ccd7f.png)

**Comment by Ben-Mathews** [comment]
Same issue on Ubuntu 20.04 using Gnome / GTK

**Comment by Elbullazul** [comment]
Will check

**Comment by jafd** [comment]
You have a bunch of assets named like `checkbox-unchecked@2.png`, but the CSS refers to them as `checkbox-unchecked-@2.png`. I could probably make a PR, the only question is if those names are generated using a script (in which case the script needs fixing) or changing them manually would suffice.

**Comment by Elbullazul** [comment]
Thank you so much for pointing this out. I had no clue why it was happening.

The correct naming is the asset one, without a dash before the '@'.

The correct way to fix this would be to submit a patch removing the dash from the SCSS function [here](https://github.com/B00merang-Project/Azurra_framework/blob/4b141a533c7178dc92c43ee3fe84803c90984537/Azurra/_functions.scss#L37), changing
`@return -gtk-scaled(url($filename + $extension), url($filename + "-@2" + $extension));`

to

`@return -gtk-scaled(url($filename + $extension), url($filename + "@2" + $extension));`

**Comment by Elbullazul** [comment]
Or I'll do it myself in the coming hours, whatever comes first

**Comment by jafd** [comment]
Just a note, _all_ themes will need to be re-generated. I'm seeing this problem in each and every theme (oh, the first-world difficulties of someone with all-HiDPI setup...)

**Comment by Elbullazul** [comment]
yeah, most of them used this function to generate asset paths. You can sumbit the change and I'll regen everything

**Comment by Elbullazul** [comment]
pushed, can anyone confirm if the bug is fixed?

**Comment by jafd** [comment]
I can confirm it's working for me.

**Comment by Elbullazul** [comment]
@jafd thank you again for finding the root of the issue.
