### ISSUE TITLE
Cortana and Expo not showing up?

### ISSUE THREAD

**Issue by GitUser445** [B00merang-Project/Windows-10#179]
In the screenshots I see the icons Cortana and expo. I have no idea how to set those up on my panel.
(Linux Mint Cinnamon 4.4.8)

**Comment by GitUser445** [comment]
Also, how do you get tiled images on your menu?

**Comment by Elbullazul** [comment]
You can customize the cinnamon applet to use a particular icon for the Expo.

Cortana is just a placeholder. 

Tiled menu was a variant of the slingshot launcher. Idk if it still works : https://github.com/elbullazul/slingshot

**Comment by GitUser445** [comment]
> You can customize the cinnamon applet to use a particular icon for the Expo.


Wait, wydm customize the cinnamon applet? I can find "Expo" applet but there is no option to change the icon.

**Comment by GitUser445** [comment]
Oh, I see what you mean. The icons are a bit stretchy, though.
![Screenshot from 2020-04-14 21-09-55](https://user-images.githubusercontent.com/54332580/79288352-79af1b80-7e94-11ea-96ae-a38920dfe059.png)

**Comment by Elbullazul** [comment]
Yeah, you can adjust the icons manually, I guess some panel sizing rules have changed
