### ISSUE TITLE
Not working on ubuntu 20

### ISSUE THREAD

**Issue by khou2020** [B00merang-Project/Windows-10#182]
The theme did not show up in the tweak
![Screenshot from 2020-05-04 18-14-05](https://user-images.githubusercontent.com/25940322/81022583-94d9cf00-8e33-11ea-9e05-bd05f8793e37.png)

**Comment by khou2020** [comment]
The zip file provided by the download link does not include the top folder so extracting them directly into .themes don't work.
The git version can be seen in tweak but only work for applications.
There's no start menu.

**Comment by feren** [comment]
You, uh, need to install it into a folder in .themes for the theme to be found.

**Comment by Elbullazul** [comment]
you move all those files to a new directory named Windows 10 and it works.

start menu needs an applet, I suggest [Arc menu](https://extensions.gnome.org/extension/1228/arc-menu/)
