### ISSUE TITLE
GtkToggleToolButtons are not styled

### ISSUE THREAD

**Issue by Parakoopa** [B00merang-Project/Windows-10#184]
Hi! Thanks for this theme!

The GtkToggleToolButton doesn't seem to have proper styling for when it's active:

In Adwaita:
![image](https://user-images.githubusercontent.com/3512122/83174448-b5d3ce00-a11a-11ea-9f0d-7aa4a5315340.png)

In this theme:
![image](https://user-images.githubusercontent.com/3512122/83174486-c421ea00-a11a-11ea-968c-e2ca8a23ac5e.png)

There is no visual difference between the activated & deactivated item.

I used this simple Gtk Builder XML file to reproduce this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.22.2 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkToolbar">
    <property name="visible">True</property>
    <property name="can_focus">False</property>
    <child>
      <object class="GtkToggleToolButton">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="label" translatable="yes">Button</property>
        <property name="use_underline">True</property>
      </object>
      <packing>
        <property name="expand">False</property>
        <property name="homogeneous">True</property>
      </packing>
    </child>
  </object>
</interface>
```

Edit: This also affects the dark version of the theme.

**Comment by Elbullazul** [comment]
If I remember correctly, I set the toolbar buttons to share the styling with the flat buttons (no style by default). I didn't consider this particular case. I'll have a look and keep you updated when changes are made.

Btw, how do I build this app? I forgot how to build from xml

**Comment by Parakoopa** [comment]
You can either use Glade (https://glade.gnome.org/) and it's preview function (it's the gears icon in the bottom left, when you select the toolbar).

Or you can use this Python script if you have Python and PyGObject:
```
from gi.repository import Gtk

window = Gtk.Window()
toolbar = Gtk.Toolbar()
toolbar_toggle_button = Gtk.ToggleToolButton.new()
toolbar_toggle_button.set_label("Button")
toolbar.add(toolbar_toggle_button)
window.add(toolbar)
window.show_all()
Gtk.main()
```

**Comment by Elbullazul** [comment]
it seems it now works as intended:

![image](https://user-images.githubusercontent.com/15310985/96195742-897aeb80-0f1b-11eb-86fb-ab0e17189d2d.png)
