### ISSUE TITLE
Bad link to b00merang page

### ISSUE THREAD

**Issue by sigmasoldi3r** [B00merang-Project/Windows-10#185]
The readme has a bad link which leads to windows 1.0 theme instead of windows 10.

The bad link is http://b00merang.weebly.com/windows-10.html
Which should be https://b00merang.weebly.com/windows-101.html

**Comment by Elbullazul** [comment]
indeed, it's a bad link. I fixed the website instead, because the URLs are very confusing. Thank you for pointing this out though
