### ISSUE TITLE
C0rtana Alternative using the Mycroft KDE Plasmoid...

### ISSUE THREAD

**Issue by msgpo** [B00merang-Project/Windows-10#187]
https://github.com/KDE/plasma-mycroft

Can this be integrated as an option for the search box AI?

**Comment by Elbullazul** [comment]
I think you should as the KDE team who maintains that plasmoid for this feature

**Comment by msgpo** [comment]
> 
> 
> I think you should ask the KDE team who maintains the plasmoid for this feature

My question/ suggestion is obviously not about the KDE team's plasmoid, its about using Mycroft for this Windows 10 Light theme for Linux in a similar way used in the KDE plasmoid for reference.

There is nothing wrong with this suggestion at least that I can tell, and no reason for you to be so sensitive about it,
