### ISSUE TITLE
Chromium logo should be left unchanged

### ISSUE THREAD

**Issue by TheAlienDrew** [B00merang-Project/Windows-10#191]
Chrome is still something that can be downloaded onto some linux systems, and having the Chromium logo changed to the Chrome logo can make things rather confusing sometimes.

**Comment by Elbullazul** [comment]
correct, action will be taken in the short future.

also, for future issues, please use the [bug tracker](https://github.com/B00merang-Artwork/Windows-10) for the icon pack

**Comment by Elbullazul** [comment]
moved to appropriate repository
