### ISSUE TITLE
Might want to use the new Notepad logo

### ISSUE THREAD

**Issue by TheAlienDrew** [B00merang-Project/Windows-10#192]
Although they are removing it as a store downloadable, they will be using the logo and updating the original notepad.exe with the new logo.

See https://www.microsoft.com/en-us/p/windows-notepad/9msmlrh6lzf3

**Comment by Elbullazul** [comment]
I don't have it yet, but I'll add it when I find some time

**Comment by Elbullazul** [comment]
moved to appropriate repository
