### ISSUE TITLE
Xfce Menu Separator

### ISSUE THREAD

**Issue by masscream** [B00merang-Project/Windows-10#193]
Hello, thank you for your work. For some reason, this is how a menu in Xfce looks like (broken separators). It was working before in another distro (Mint Xfce), now I switched to Debian and this is the result. It may be also the version issue... Now using 4.12.

![broken xfce separator](https://i.imgur.com/i2CDtz7.png)

**Comment by Elbullazul** [comment]
Will have a look asap

**Comment by Elbullazul** [comment]
![image](https://user-images.githubusercontent.com/15310985/100167979-5454a800-2e8e-11eb-91b7-b01739a2f8e8.png)

looks good in 4.14. Sorry for the delayed response
