### ISSUE TITLE
Missing radiocheck boxes on one computer

### ISSUE THREAD

**Issue by tonydiep** [B00merang-Project/Windows-10#194]
On one of my computers the theme doesn't show combo boxes in menus

For instance Nautilus should show
Sidebar [ ]
but the combo box does not show. 
Other themes show the combo box properly.

**Comment by tonydiep** [comment]
The release from 2017 shows the combo box properly.
https://www.gnome-look.org/p/1216281/

**Comment by Elbullazul** [comment]
Please upload an image of the issue,  and another one of how it's supposed to look

**Comment by tonydiep** [comment]
## Missing combo box beside 'Sidebar', missing lines between menu items
![Missing combo box beside 'Sidebar'](https://user-images.githubusercontent.com/705269/99525557-f85ac280-2967-11eb-86a3-be090401b3a3.png)


## How it's supposed to look
![How it's supposed to look](https://user-images.githubusercontent.com/705269/99525704-2f30d880-2968-11eb-99a5-b653c9d50a59.png)

**Comment by Elbullazul** [comment]
do you see the checkbox in other apps? For example, in the settings for Gedit (text editor).

I want to know if the issue is only for this type of menu or a theme-wide issue

**Comment by tonydiep** [comment]
I do see it in other apps. For instance with the screenshot tool radio buttons are missing. Using the Windows-10-master variant fixes it.

**Comment by Elbullazul** [comment]
are you using a [release version](https://github.com/B00merang-Project/Windows-10/releases)? If so, which one?

**Comment by tonydiep** [comment]
This happens on release version 10.3.2
Centos 8.2
Gnome Version 3.32.2
Intel® HD Graphics 515 (Skylake GT2)

**Comment by Elbullazul** [comment]
where did you get the theme from?

**Comment by tonydiep** [comment]
To make sure we're talking about the same release, I downloaded it from the link you provided and confirmed that the problem is there.

**Comment by Elbullazul** [comment]
ok, just wanted to make shure it was not an old version of the theme.

I'll have a look at this later today

**Comment by tonydiep** [comment]
The problem does not appear on my desktop with AMD® Verde graphics
But does appear on my laptop with Intel® HD Graphics 515 (Skylake GT2) graphics
Both computers are Centos 8.2 on Gnome Version 3.32.2

**Comment by Elbullazul** [comment]
oh dear. if you run

```shell
killall nautilus
nautilus
```

in the terminal, do any errors show up?

**Comment by tonydiep** [comment]
Here's something that should help triage. The problem appears in Wayland. But it does not appear under X11

**Comment by tonydiep** [comment]
I have tried killing nautilus and restarting nautilus. The problem still occurs. The problem happens in other programs such as the gnome screenshot program.

**Comment by Elbullazul** [comment]
I want to know if there is any error messages when you open it from the terminal after killing it. Do you get any?

**Comment by tonydiep** [comment]
There are no error messages

**Comment by Elbullazul** [comment]
does the latest master fix this? 2cdf207 addresses the issue

**Comment by Elbullazul** [comment]
https://github.com/B00merang-Project/Windows-10/issues/178 is related and fixed, assuming it fixes this as well (can't test HiDPI myself)

**Comment by tonydiep** [comment]
I can confirm the current master on Github fixes the problem. The check boxes and radio buttons are visible. Thank you very much for fixing it!
