### ISSUE TITLE
taskbar in white ?

### ISSUE THREAD

**Issue by PowaBanga** [B00merang-Project/Windows-10#195]
Hi, I have this windows 10 theme in white on my archlinux (cinnamon)

this is my pkbuild : 
```
pkgname=b00merang-windows-10-gtk-theme
pkgver=3.2
pkgrel=1
pkgdesc="A b00merang-windows-10-gtk-theme"
arch=('any')
url="https://github.com/B00merang-Project/Windows-10/releases"
license=('GPL')
depends=('gtk3')
source=("https://github.com/B00merang-Project/Windows-10/archive/3.2.tar.gz")
md5sums=('105f5aa25dca01f390705f959b888d87')

package() {
	cd ${srcdir}/
	mkdir -p ${pkgdir}/usr/share/themes
	cp -r Windows-10-3.2 ${pkgdir}/usr/share/themes
	cd ${pkgdir}/usr/share/themes
	mv ${pkgdir}/usr/share/themes/Windows-10-3.2 ${pkgdir}/usr/share/themes/Windows-10
	chown -R root:root ${pkgdir}/usr/share/themes
}
```

![](https://i.imgur.com/NDGL1up.png)

Normal the taskbar and menu should be in dark ...:/

**Comment by Elbullazul** [comment]
ah yes. I switched that a while back thinking Microsoft would have made the Windows 10 taskbar white as in these screenshots:
![img](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.thurrott.com%2Fwp-content%2Fuploads%2Fsites%2F2%2F2018%2F11%2Fvmplayer_2018-11-14_19-24-29.png)

I'm really uncertain on what to do with this. Same thing for the dark variant colors, no idea what I should use as a template. I'll probably revert to the default black taskbar in a few days.

In the meantime, you can use the cinnamon theme from the [Windows 10 Dark theme](https://github.com/B00merang-Project/Windows-10-Dark)

**Comment by PowaBanga** [comment]
haa yes, ok, thank you very much.

But do you know if there is a windows10 icon theme addapted for your win10 theme ? because it seem that the icon theme that i have is for dark theme only...

**Comment by Elbullazul** [comment]
https://github.com/B00merang-Artwork/Windows-10-Dark

**Comment by PowaBanga** [comment]
Ok, i take note of your answer, thank you very much.

But i think that you did understood my question.

In your link i can find a windows 10 icons theme addapted to windows 10 dark theme, but it is exactly the same that this one : https://github.com/B00merang-Artwork/Windows-10
and they are not addapted to windows 10 light theme -> white icons are on white task bar... i can't see them.

And so, i have a new question, because i installed [windows 10 theme](https://github.com/B00merang-Project/Windows-10) on a fresh install of my archlinux, and the theme is in blak here... So my question is : is there a way and how to make my windows-10-gtk-theme in light/white ? :)

**Comment by Elbullazul** [comment]
If you want a dark variant for apps, try https://github.com/B00merang-Project/Windows-10-Dark

**Comment by PowaBanga** [comment]
🧐

I am looking for a light variant too now 😊

**Comment by Elbullazul** [comment]
I'm not sure I understand you. You wanted a light theme to go with the light panel?

**Comment by xsrvmy** [comment]
> ah yes. I switched that a while back thinking Microsoft would have made the Windows 10 taskbar white as in these screenshots:

Win10 has a native customization option now for light taskbar (not sure if it is in home edition or only pro edition)
