### ISSUE TITLE
Linux Mint 20.2 Cinnamon: Shutdown dialog looks ugly

### ISSUE THREAD

**Issue by stefan-niedermann** [B00merang-Project/Windows-10#199]
Dear @Elbullazul 

thanks for this great theme! Makes it a lot easier to migrate my grandma™ to linux :wink: 

I noticed that the shutdown dialog (as well as the logout dialog) look a bit weird on Linux Mint 20.2 Cinnamon.

While i am not sure what it is supposed to look like, the `#cc0000` looks out of place and is very hard to read due to the low contrast with the `#000000` font:

![shutdown](https://user-images.githubusercontent.com/4741199/129681850-480638b7-3ee8-464f-a6ed-8e8ea2e8ff42.png)

Here a reference to the original:

![grafik](https://user-images.githubusercontent.com/4741199/129682451-793e245b-7fd9-4068-a21e-a9b4a7d9ed89.png)

I know, theming is limited, but maybe we can at least remove the `#cc0000` background color and add some padding to the buttons?

_ | _
--- | ---
Operating system | Linux Mint 20.2 Cinnamon
Cinnamon version | 5.0.5
Linux kernel | 5.4.0-81-generic
CPU | Pentium Dual-Core CPU E5300 @ 2.60GHz * 2
RAM | 3.7 GiB
GPU | Intel Corporation 4 Series Chipset Integrated Graphics Controller

Keep up the great work :rocket:

**Comment by Elbullazul** [comment]
I'll see what I can do next time I work on Cinnamon themes

**Comment by stefan-niedermann** [comment]
I am quite familiar with css (i am a web developer), so i could make a PR if you want - i just need some help about the possible selectors and available classes i can hook on. Unfortunately i havem't written such a theme before and i couldn't find a documentation. Or maybe there is something similar to the browser dev tools where one can inspect the "dom"?

**Comment by Elbullazul** [comment]
@stefan-niedermann to inspect Cinnamon, there is this tool called 'looking glass', I think it's launched with the `lg`. However, if I remember correctly that dialog is a GTK app, launched with the command `cinnamon-session-quit`. To inspect GTK apps, you have to launch the app with the Inspector, like this: `GTK_DEBUG=interactive cinnamon-session-quit`.

**Comment by Elbullazul** [comment]
Also, I want to say I'm unsure of the future of the project, mostly because of the potential changes to GNOME and the uncertainty on what that means for GTK themes. Maybe rebasing everything on Adwaita would be a way of future-proofing the themes, but I currently don't have the time to work on that.

**Comment by dominichayesferen** [comment]
> Also, I want to say I'm unsure of the future of the project, mostly because of the potential changes to GNOME and the uncertainty on what that means for GTK themes. Maybe rebasing everything on Adwaita would be a way of future-proofing the themes, but I currently don't have the time to work on that.

You could always move to making Qt themes. Also, no amount of forking Adwaita will future-proof your themes at this point when they've gone as far as having a GTK+5 consideration to remove themes entirely.

**Comment by Elbullazul** [comment]
@drrible moved issue here, as it's unrelated. Also, no need to be rude

**Comment by Elbullazul** [comment]
I'm going to close this issue, as I don't think making important app-specific customizations is a good idea

**Comment by stefan-niedermann** [comment]
Playing around a little bit I'd like to document my results here in case someone has an idea (even though this issue has been closed - it still is the last remaining really ugly part in this theme using cinnamon).

1. The dialog currently has the color `#cc0000` and `#a30000` on hover
2. The hover color does not appear anywhere in the theme - maybe it is generated though with some magic stuff
3. Replacing *all* occurrences of `#cc0000` with another color like ´#0000cc` did not change the look of this dialog

I expected that step three would make some kind of difference, because the color is only `#cc0000` when the windows 10 theme is active...

**Comment by Elbullazul** [comment]
@stefan-niedermann I believe what you're searching for is here: https://github.com/B00merang-Project/Windows-10/blob/master/gtk-3.20/gtk.css#L2423
