### ISSUE TITLE
TwisterOS GPL infringement 

### ISSUE THREAD

**Issue by neofeo** [B00merang-Project/Windows-10#200]
Hi, I would like if you want take a look on the themes from  this popular custom image for RPI4 and other devices bc they took some parts of this work and never shared the changes on a publicly available repository.

It's  also available for x86_64  pcs.

[TwisterOS](https://www.twisteros.com) 

I know you do this for fun, but this guys are taking your work and not respecting your GPL 3 terms. I also know you may not be able to do much. 

BR.

**Comment by Elbullazul** [comment]
I appreciate your concern.

GTK themes are open by nature if not bundled in a binary format, so even though they don't have a repo of the changes, the modified code is available if you open up the theme files once the distro is installed.

I also don't think they do it maliciously, it seems the project is small, so maybe they just don't have the time to maintain repos and that kind of stuff.

I personally made these themes with the idea of them being freely available and reusable, so I don't really mind the guys at Twister using my work
