### ISSUE TITLE
Desktop's font text is black

### ISSUE THREAD

**Issue by rubensheik** [B00merang-Project/Windows-10#202]
Hello, thanks for your awesome theme, i'm really enjoying, but there is just this issue that i couldn't find a solution, where in css can i change this color to white?

![image](https://user-images.githubusercontent.com/97188294/148265519-68a65532-1d08-48ae-b7a5-0cf1fb2d1bf5.png)

I'm using Linux Lite 5.6 XFCE Desktop with Windows 10 GTK Theme

Thank you.

**Comment by Elbullazul** [comment]
Hi, thanks for pointing this out. I'll have a look asap, because desktop text is supposed to be white

**Comment by rubensheik** [comment]
Thank you!

**Comment by rubensheik** [comment]
Hello @Elbullazul 
Maybe there is some simple way to solve this that myself can apply? 
I'm using your theme to customize a iso, and we'll deploy it in a lot of computers about next week!
Thanks for you attention.

**Comment by Elbullazul** [comment]
If you're familiar with CSS and gtk inspector, you can have a look at the `XfdesktopIconView .view {` block. I'm currently having a look at this, so I'll let you know if I manage to correct it

**Comment by Elbullazul** [comment]
I finished installing Linux Lite and it seems to work OK. Are you using the latest release? If so, the fix to the Xfce desktop text is not included. I'll create a new release with the fix

**Comment by Elbullazul** [comment]
![image](https://user-images.githubusercontent.com/15310985/151682222-f24c025f-328a-428d-83ce-f8209325866a.png)

how it looks with release [3.2.1](https://github.com/B00merang-Project/Windows-10/releases/tag/3.2.1)

**Comment by rubensheik** [comment]
I'll install again! Thank you.

**Comment by Elbullazul** [comment]
anything new?
