### ISSUE TITLE
issue with desktop icons on manjaro

### ISSUE THREAD

**Issue by SkrudjReal** [B00merang-Project/Windows-10#206]
my system is Linux God 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux

XFCE4

theme - https://www.xfce-look.org/p/1013482

![Screenshot_2022-05-19_17-25-24](https://user-images.githubusercontent.com/76687908/169338896-e1786853-fcd3-483c-9ef6-fffd4fab6512.png)
 
![Screenshot_2022-05-19_17-53-32](https://user-images.githubusercontent.com/76687908/169345616-19133551-53c3-4715-bb77-6d6187e1a747.png)

**Comment by Elbullazul** [comment]
I'll look into it

**Comment by Elbullazul** [comment]
sorry for the delay. Does [v3.2.1](https://github.com/B00merang-Project/Windows-10/releases/tag/3.2.1) fix it?

**Comment by Elbullazul** [comment]
I'm going to assume it does

**Comment by drustan14** [comment]
+1 3.2.1not correct this
