### ISSUE TITLE
[feature-request] repository 'community' in organization B00merang-Project with option 'Discussions' enable

### ISSUE THREAD

**Issue by codehangen** [B00merang-Project/Windows-10#208]
Hi! Hey! Would it be possible for someone to create a repository of ideas for anyone or developers to talk about the topics they like, created?

#### Just like that?
![image](https://user-images.githubusercontent.com/111701513/187321632-a863c992-a695-400b-8028-874da10e130f.png)

This would allow anyone to comment on the topics without necessarily having to open an issue. Also, this option allows you to transfer discussions between different repositories if each repository has this option enabled. Maybe in the future we could create open design standards for any linux user something like: [human-interface-guidelines/foundations/app-icons](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons) as "boomerang-project .com/design/human-interface-guidelines/themes" ?

If anyone can answer, I'm waiting for an answer

**Comment by Elbullazul** [comment]
hi,

sounds interesting. I'm curious to know what kind of topics you'd like to discuss ?

**Comment by Elbullazul** [comment]
sounds interesting, but not sure of enabling it on every repo. Would be great if there was one 'discussion' for the whole b00merang organization

**Comment by Elbullazul** [comment]
[found out that feature exists](https://docs.github.com/en/organizations/managing-organization-settings/enabling-or-disabling-github-discussions-for-an-organization)

discussion open at https://github.com/orgs/B00merang-Project/discussions
