### ISSUE TITLE
Unity Top Panel VPN connected icon not showing 

### ISSUE THREAD

**Issue by fatihusta** [B00merang-Project/Windows-10#31]
OS: Ubuntu 16.04 - Unity 7 

Windows İcon
![screenshot from 2016-05-16 15-11-22](https://cloud.githubusercontent.com/assets/11256228/15289107/8d0f5bdc-1b78-11e6-9bff-20fe8ff2f764.png)

Ubuntu Mono dark
![screenshot from 2016-05-16 15-11-54](https://cloud.githubusercontent.com/assets/11256228/15289112/957aa04c-1b78-11e6-9bda-5faa3a3d5581.png)

**Comment by Elbullazul** [comment]
Missing icon : I'll try to fix by the next release

**Comment by Elbullazul** [comment]
say, could you try the fix? I don't even know if it will work.

If you want to, here's the download link. Extract the files to Windows 10 Icons/scalable/status
http://www.mediafire.com/download/98z8qm2oyfme77m/status.zip

and then reapply the icon theme. I think it should work

**Comment by fatihusta** [comment]
i tested but not working.

```
[status]$ ls -alh nm-vpn-*
lrwxrwxrwx 1 fatih fatih   15 May 25 18:59 nm-vpn-lock-active.svg -> nm-vpn-lock.svg
-rw-rw-rw- 1 fatih fatih  973 May 28  2014 nm-vpn-lock.svg
-rw-rw-rw- 1 fatih fatih 2,3K May 25 10:27 nm-vpn-standalone-lock.svg
[status]$ 
[status]$ 
[status]$ pwd
/usr/share/icons/Windows 10 Icons/scalable/status
[status]$ 

```

**Comment by Elbullazul** [comment]
add execution privileges to the new added icons. sometimes it works...

**Comment by fatihusta** [comment]
I changed permission and owner but nut working.

```
[status]$ ls -lah nm-vpn-*
lrwxrwxrwx 1 root root   15 May 25 18:59 nm-vpn-lock-active.svg -> nm-vpn-lock.svg
-rwxrwxrwx 1 root root  973 May 28  2014 nm-vpn-lock.svg
-rwxrwxrwx 1 root root 2,3K May 25 10:27 nm-vpn-standalone-lock.svg
[status]$ 

```

**Comment by Elbullazul** [comment]
Could you do me a favor? Make a copy of mono dark and Try to find the VPN icon by renaming whatever icon looks like the VPN one,  one by one,  and reapplying the icon theme each time you rename a file.  

I think it will be easier for you to find the icon,  since you have a VPN and I don't. 

If you find the icon,  please post the original name and the path

**Comment by Elbullazul** [comment]
Have you found out something?

**Comment by fatihusta** [comment]
Hi
Sory, I'am late, because very busy with my job.

I searched into ubuntu-mono-dark and i found some icons. 
Every settings for 16x16 and 22x22 and 24x24 
I tested 22x22 

1- VPN Connection animations
//links
```
cp /usr/share/icons/ubuntu-mono-dark/animations/22/nm-vpn-connecting* ~/.icons/Windows\ 10\ Icons/22x22/animations/
```
//images
```
cp /usr/share/icons/ubuntu-mono-dark/animations/22/nm-stage01-connecting ~/.icons/Windows\ 10\ Icons/22x22/animations/
```

2- VPN Secure lock
//sample different secure icon

//Wired Secure
```
cp /usr/share/icons/breeze/devices/22/network-wired-unavailable.svg ~/.icons/Windows\ 10\ Icons/22x22/status/
```
//Wireless Secure
```
cp /usr/share/icons/ubuntu-mono-dark/status/22/nm-signal-*-secure* ~/.icons/Windows\ 10\ Icons/22x22/status/
```
Worked for me.


3- Other VPN Secure lock - (No my case)
//Links
```
cp /usr/share/icons/ubuntu-mono-dark/status/22/nm-secure-lock.svg ~/.icons/Windows\ 10\ Icons/22x22/status/
cp /usr/share/icons/ubuntu-mono-dark/status/22/nm-vpn-active-lock.svg ~/.icons/Windows\ 10\ Icons/22x22/status/
```
//Images
```
cp /usr/share/icons/ubuntu-mono-dark/status/22/nm-vpn-lock.svg ~/.icons/Windows\ 10\ Icons/22x22/status/
cp /usr/share/icons/ubuntu-mono-dark/status/22/nm-vpn-standalone-lock.svg ~/.icons/Windows\ 10\ Icons/22x22/status/
```

**Comment by Elbullazul** [comment]
I think I have fixed this error with the next icon pack (v0.5)

**Comment by Elbullazul** [comment]
oh, well...

I think the icons got lost somewhere, they`re not there anymore >/

sorry to having you wait so long, but I`ll get these icons to work!

**Comment by Elbullazul** [comment]
here is the new icon pack, I included all VPN-related icons found in humanity/ubuntu icons themes, so I think this should do it. [rolling](https://github.com/B00merang-Project/Windows-10/archive/icons.zip)

P.S. sometimes for the icons to work you need to log out and back in, for some reason :/

**Comment by fatihusta** [comment]
I did logut and login
I tested wired connection but not working. 
I tested Wireless Connection and worked but Secure icons looks wrong
![wifi_secure_icon](https://cloud.githubusercontent.com/assets/11256228/19338534/543e5e4c-9126-11e6-903f-da7f5080604f.png)

and we have a similar problem.
Connection animation icons so old
![connection_processing](https://cloud.githubusercontent.com/assets/11256228/19338336/11422ee4-9125-11e6-98f8-c6096a158ebd.png)

**Comment by Elbullazul** [comment]
icons migrated to https://github.com/B00merang-Artwork/Windows-10
