### ISSUE TITLE
Wifi and wired network icons problem

### ISSUE THREAD

**Issue by fatihusta** [B00merang-Project/Windows-10#32]
wifi and wired network icons problem

![nework-icon](https://cloud.githubusercontent.com/assets/11256228/15547295/e4c9e736-22ab-11e6-8704-7785a61d65e1.png)

**Comment by Elbullazul** [comment]
did it happened with the previous release too or is it an update problem?

**Comment by fatihusta** [comment]
I installed only this deb package 
https://github.com/Elbullazul/Windows-10/releases/download/v0.9.6/windows-10-tp_0.9-6.amd64.deb

**Comment by Elbullazul** [comment]
I've had problems with the Deb since before I created it,  I guess it's privileges again...

**Comment by Elbullazul** [comment]
Try this: uninstall the deb package and install the Transformation Pack with the shell script I built : https://www.gnome-look.org/p/1013482/

I think it should solve permissions if that's the problem. Otherwise, it's some icons gone missing (again!)

**Comment by fatihusta** [comment]
I downloaded again. 

I removed manualy. 
```
sudo rm -rf /usr/share/themes/Windows\ 10\ Light/
sudo rm -rf /usr/share/icons/Windows\ 10\ Icons/
```

And install manualy into home folder.
```
mkdir ~/.themes ~/.icons
cp -a Downloads/Windows\ 10\ Light/ ~/.themes/
cp -a Downloads/Windows\ 10\ Icons/ ~/.icons/
```

But same result. :(

**Comment by Elbullazul** [comment]
I conclude some  icons are missing.  I'll try to add them when I can

**Comment by feren** [comment]
Hmm, try looking in elementary's icon set, they most likely have the names of the icons your missing from  the set in its own icon set...

sudo apt install elementary-icon-theme (If you have the elementary OS repo)

**Comment by Elbullazul** [comment]
Found how to correct this.  Next icon pack will include fixes

**Comment by cinnamoner** [comment]
> Found how to correct this. Next icon pack will include fixes.

@Elbullazul 
Looking forward to it. I'll check them one by one.

**Comment by Elbullazul** [comment]
very sorry for the delay, have (re) found the icons necessary, just need to link them to correct ones in existing icon set, and we're ready to go

again, sorry for taking this much time to fix this

**Comment by fatihusta** [comment]
Not important. Thank you.

**Comment by Elbullazul** [comment]
[Rolling-release-icons](https://github.com/B00merang-Project/Windows-10/archive/icons.zip) includes the new wifi icons, may need to log out and back in for them to show correctly

**Comment by fatihusta** [comment]
I tested but we have 2 small problem.
1- Secure icon is so old
2- Ligth theme looks that
![menu_001](https://cloud.githubusercontent.com/assets/11256228/19338170/d3f40568-9123-11e6-908c-095558a6e450.png)

**Comment by feren** [comment]
@Elbullazul You may want to Trace Bitmap the icons into SVGs and use the good old bebebeff trick on them to make them work properly...

**Comment by Elbullazul** [comment]
still looking for a solution. Inkscape doesn't trace well, and I don't want to redraw every thing one by one

@feren maybe you can help me trace, if you have time?

**Comment by fatihusta** [comment]
Hı
I have a solution. 
Looks like
![menu_001](https://cloud.githubusercontent.com/assets/11256228/19845915/2bcb96c4-9f44-11e6-9de0-6d653f4f503f.png)


Files: 
[win10-light-theme-secure-and-wifi-icons-example.zip](https://github.com/B00merang-Project/Windows-10/files/561207/win10-light-theme-secure-and-wifi-icons-example.zip)


I think scalable/status icons and 22x22/animations icons enough. But I'am not sure.
Maybe some other case need other size icons. 16x16 and 24x24

Not: Every icons is sample. Specialy nm-device-wired-secure icon.

**Comment by Elbullazul** [comment]
mmm, looks interesting

have you found the vpn icon too?

**Comment by fatihusta** [comment]
I could not find it. :(
So, I'm using different wired icon. (nm-device-wired-secure)

**Comment by Elbullazul** [comment]
icons migrated to https://github.com/B00merang-Artwork/Windows-10
