### ISSUE TITLE
Window Button Compiz Transparency Issue

### ISSUE THREAD

**Issue by annoyingduck** [B00merang-Project/Windows-10#50]
All details can be found here, along with a description from a user of what the issue is: https://forum.manjaro.org/t/how-to-adjust-compiz-metacity-transparency-after-new-update/6896
![screenshot_2016-08-02_14-40-27](https://cloud.githubusercontent.com/assets/20876335/17457520/419272da-5bc8-11e6-97ba-461005512bf2.png)

**Comment by Elbullazul** [comment]
Ok,  I'll have a look at the solution proposed. 

Thanks for your feedback

**Comment by albertsmuktupavels** [comment]
Any reason why you are using images? At least titlebar images can be replaced with <rectange /> and <line />.

**Comment by Elbullazul** [comment]
Yes, it's just a remanent of the original theme,  when i was learning metacity

I'll implement this in the next version

**Comment by feren** [comment]
@Elbullazul 
Next time, try using an SVG instead...

**Comment by Elbullazul** [comment]
all assets for window-borders are now replaced with XML elements. next release will include all these corrections

**Comment by annoyingduck** [comment]
Awesome, thank you. It's the only window theme I like to use. Looking
forward to going back to Metacity over Emerald (I like it better).  Thanks
again.

On Tue, Oct 11, 2016 at 3:49 PM, B00merang Project <notifications@github.com
