### ISSUE TITLE
Bad color/inadequate highlighting on icon hover

### ISSUE THREAD

**Issue by cinnamoner** [B00merang-Project/Windows-10#63]
@Elbullazul Whenever I hover the icons they glow up and almost blend in with the background which is waaay too bright. Can only use the theme with shades. Light blue border 'round the icons and the background somewhat softer. There you go.
![screenshot from 2016-10-03 20-38-22](https://cloud.githubusercontent.com/assets/15638605/19047681/9218d684-89ab-11e6-8d5d-96cc0d92e8c0.png)
![screenshot from 2016-10-03 20-39-08](https://cloud.githubusercontent.com/assets/15638605/19047685/9670e014-89ab-11e6-96b0-caa58b261d95.png)

**Comment by cinnamoner** [comment]
@Elbullazul No, it's not my monitor.

**Comment by cinnamoner** [comment]
@Elbullazul Why that slider? Please look into Plasma. Nice n round, please. It's way too angular.

**Comment by cinnamoner** [comment]
![screenshot from 2016-10-03 21-20-08](https://cloud.githubusercontent.com/assets/15638605/19048499/3c168b6a-89af-11e6-9286-6a18fddcf1bc.png)
@Elbullazul Under my computer, you use a light blue for highlighting. That's cool bro, but try like real pale blue with a slightly darker border.
Why do you use multiple highlighting methods?

**Comment by cinnamoner** [comment]
@Elbullazul The tooltips bled in with the background and the view buttons are too minimalistic. the theme is too bright. Can you make it softer?

**Comment by Elbullazul** [comment]
@cinnamoner I, huh, can make a semi-gray theme if that's what you want

hover states differ based on the widget that's used. Sidebar uses row, icons use iconview. somehow they have different shading methods

**Comment by cinnamoner** [comment]
@Elbullazul No gray. Can't you play RGB, Hex? .... there's too much blue in that white.

**Comment by Elbullazul** [comment]
wait, you want the hover blue darker?

**Comment by cinnamoner** [comment]
@Elbullazul Yeah but why do the folders glow. It ain't happening in Windows.

**Comment by cinnamoner** [comment]
> wait, you want the hover blue darker?

No.

**Comment by cinnamoner** [comment]
@Elbullazul The folders should be highlighted as whrere's the pointer in the 3rd shot instead of glow. No glow.

**Comment by cinnamoner** [comment]
This is such a nice theme but has a few things wrong.

**Comment by cinnamoner** [comment]
Same glow with some Vista icons. That glow is bad.
![screenshot from 2016-10-03 22-50-51](https://cloud.githubusercontent.com/assets/15638605/19051538/09c2a024-89bc-11e6-8855-ceba4dc46cf8.png)

**Comment by cinnamoner** [comment]
![screenshot from 2016-10-03 22-54-59](https://cloud.githubusercontent.com/assets/15638605/19051677/77e5ca2c-89bc-11e6-93af-d4e4b61e3e4d.png)

**Comment by cinnamoner** [comment]
![screenshot from 2016-10-03 22-56-51](https://cloud.githubusercontent.com/assets/15638605/19051741/b4c8b53a-89bc-11e6-8bb4-9e89173253d1.png)

**Comment by cinnamoner** [comment]
> Bad color on hover (Iconview)

@Elbullazul You bet. Look into Windows.

**Comment by Elbullazul** [comment]
I'll need to investigate a bit. I don't know if it can be changed though

**Comment by cinnamoner** [comment]
Wait

**Comment by cinnamoner** [comment]
Wait

**Comment by cinnamoner** [comment]
@Elbullazul Is there a setting in Cinnamon I'm not aware of?

**Comment by cinnamoner** [comment]
@Elbullazul _Hover-glow_ is a bad method for highlighting folders. So is the _hover-ghost_ method in the _System Settings_ shots right upstream. You use _hover-ghost_ in other places as well. Nay.

**Comment by feren** [comment]
It affects all of GTK, including Nautilus...

**Comment by cinnamoner** [comment]
@Elbullazul Promised feedback :) No worries.

> It affects all of GTK, including Nautilus...

@feren No workaround? This is terrible! One can go blind with that damn glow.

**Comment by cinnamoner** [comment]
@feren Hover a folder in Windows Vista/7/8.x/ ... it's different, right?

**Comment by cinnamoner** [comment]
@Elbullazul @feren @bluedxca93
All I'm saying, for starters, this is not how it works in Windows. It must happen as in Windows.

**Comment by cinnamoner** [comment]
> I don't know if it can be changed though

@Elbullazul Then give up the damn thing. You've been doing it for more than a year. Do you wanna go blind? Really? Ain't worth it. Unless there's a workaround.

**Comment by Elbullazul** [comment]
maybe it's possible, but I don't know the class needing the correction :$

**Comment by cinnamoner** [comment]
> I don't know the class needing the correction

@Elbullazul Then get to know it. Cause this is your best theme and I don't want it to be waisted work. I'll pinpoint all it's shortcomings. What I think I say. Concentrate on this one. It's the only one that matters.

**Comment by cinnamoner** [comment]
@Elbullazul Any news on the class controlling the thing. And well, if you're still interested in the key theme it's now the time to get it right. You have my full support.

**Comment by cinnamoner** [comment]
I'll be back. I don't wanna admit the theme is still not good enough. But it could be. Just listen to my advices and will be. It transcends our persons. Our feelings have nothing to do with it. Nothing.

**Comment by cinnamoner** [comment]
@feren Does this glow happen in plasma as well?

**Comment by Elbullazul** [comment]
think it does, it's embedded into the FM

**Comment by cinnamoner** [comment]
Hmm. Kinda figured. So pretty much everything glows up when hovered in Linux. But the yellow folders are the worst case.

**Comment by cinnamoner** [comment]
So, No hover-glow. No hover-ghost. Those are the issues to be dealt with.

**Comment by cinnamoner** [comment]
@bluedexca93 Any ideas?

**Comment by bluedxca93** [comment]
@cinnamoner maybe but im not able to test today.
some mostly minor updates on ice theme for 3.20 version. I think.after
tommorow.im able to fix the bugs mentioned earlier.

**Comment by cinnamoner** [comment]
Pale blue rectangle with slightly darker thin border, like in Windows@Elullazul

**Comment by cinnamoner** [comment]
> I think.after tommorow.im able to fix the bugs mentioned earlier.

@bluedxca93 Thank you. I'm astonished that nobody has ever mentioned them out before me. They are so obvious.

**Comment by Elbullazul** [comment]
@cinnamoner NEMO works it out so that there isn't a box around the icon. It's just a text zone with an icon on top of it, no "row" or "Columns"

you could search a FM that uses that kind of display so we could use it for the TP, if you want to

**Comment by cinnamoner** [comment]
@Elbullazul Just checked again Windows. No glow upon hover. Just a pale blue rectangle. Then when you click on the folder, the rectangle becomes more saturated. Then, if you take the pointer away, becomes less saturated but not as pale as on hover. Please experiment in Windows. Should I post screenshots? I don't think it's necessary but if it is then your wish is my command. I won't let you until it's perfect :) I won't let your work go to waist. It's been a long time and a lot of effort on your part. The same holds for the Vista theme. That's that.

**Comment by cinnamoner** [comment]
@Elbullazul Oh, and no ghostly overlay upon hover in settings or elsewhere either.

**Comment by cinnamoner** [comment]
@Elbullazul Yeah but maybe there's a workaround for Nemo. What file manager in Linux would act differently by the way?

**Comment by Elbullazul** [comment]
don't know, maybe feren or bluedxca know, I only know spacefm, konkeror, dolphin, nemo, nautilus, pantheon files, pcmanfm

**Comment by feren** [comment]
@cinnamoner @Elbullazul Same here.

**Comment by cinnamoner** [comment]
@Elbullazul It might have winicons but it still doesn't look or feel like it. Then there's the tooltips and the background. How do you modify the background to make it a milder white? Hex? One by one. It's futile to cover all known DE's. Narrow it down and give depth. Also, expanding the portfolio of themes hasn't had a beneficial effect on K theme. It al started on Look when you released Se7en saying it was a once off without LTS. Now we have lots but none is there. Keep in mind that you're very close to it. Some more and you're there. With the K theme that is. It's been fun but drop all other themes. K theme is plentiful when done right to the last nail. Might wanna keep just one more theme. But no more than 2. Just my advice. Take it and success is guaranteed. Then all you'll have to do will be maintenance. It's humanly impossible from you to run for on corner of Git to the next because the theme brakes on whatever DE and on whoever's system. One gets tyred after a while and looses apetite. Narrower on the horizontal and deeper on the vertical. Peace.

**Comment by cinnamoner** [comment]
@feren In Nemo. Consider the rectangle and the icon 1 piece. Would a layered structure work?

**Comment by feren** [comment]
@cinnamoner Possibly.

**Comment by cinnamoner** [comment]
It's futile to list the file managers in Linux. Better tell which would work for this particular case.

**Comment by Elbullazul** [comment]
@cinnamoner maintaining themes is far less exciting than creating them

**Comment by cinnamoner** [comment]
Then create them perfect and let the boring part to me.

**Comment by cinnamoner** [comment]
I'll be back with the blue rectangles issue.

**Comment by cinnamoner** [comment]
@Elbullazul 
I'm sure the K theme will be a nice work environment for me pretty soon. Cause I use my machine to do things. It's not a purpose in itself.

**Comment by cinnamoner** [comment]
@Elbullazul Any braketrough concerning these issues right here?

**Comment by Elbullazul** [comment]
not yet, I was working on [Royale Dark](https://github.com/Elbullazul/Redmond-Themes/releases/tag/25%2F9%2F2016) and [Whistler](http://b00merang.weebly.com/windows-whistler-watercolor.html)

**Comment by cinnamoner** [comment]
> Just checked again Windows. No glow upon hover. Just a pale blue rectangle. Then when you click on the folder, the rectangle becomes more saturated. Then, if you take the pointer away, becomes less saturated but not as pale as on hover. 

> Oh, and no ghostly overlay upon hover in settings or elsewhere either.

**Comment by cinnamoner** [comment]
@Elbullazul Okay, I understand. This is a particularly difficult issue cause it not only concerns hover but the whole range of mouse actions. It's important too, cause without it solved there's no Windows feel (nor even look). Wouldn't you agree @zerophase?

**Comment by cinnamoner** [comment]
@Elbullazul Any concept of how this issue could be solved yet?

**Comment by feren** [comment]
@cinnamoner Maybe a Nemo Feature Request...

**Comment by cinnamoner** [comment]
@feren Sure, they will implement that feature in Cinnamon pretty soon. Like in a decade from now if ever. I've seen all your suggestion addressed to Mint. Yeah, by the time you'll be like 80 years old, there's a fair chance some of those will be implemented :) What's the hurry anyways, right? We've got time, don't we?

**Comment by cinnamoner** [comment]
@Elbullazul The solution is not at Mint. If you could somehow find a workaround, that would be great. But we still haven't used the _won't fix_ label, have we? If not in Nemo, then in Caja? This is not a bug, it's a shortcoming of the file manager.

**Comment by cinnamoner** [comment]
Hey, the Vista icons actually look better than 10's. Hmmm. Contemplating on mobile. On mobile everything looks better.

**Comment by cinnamoner** [comment]
I'm sure things will get better. Rest. Thanks.

**Comment by brandleesee** [comment]
People, I was thinking about this issue and found this particular [URL].(https://wiki.ubuntu.com/Ayatana/DoubleClick)

> The blue overlay indicates draggability, already selected items have an overlay with a darker shade of blue.

This got me thinking that maybe the glow could have underlying significance? Just like the blue means draggability?

Just a silly gif!

![animation](https://cloud.githubusercontent.com/assets/12674437/19270240/486535a4-8fbf-11e6-80ad-1b08d1fcdad3.gif)

@Elbullazul probably I'm better off testing :P

**Comment by Elbullazul** [comment]
@brandleesee probably, that's a good theory

still searching if it's really in the gtk theme

**Comment by Elbullazul** [comment]
This is embedded into the file manager. Sorry

**Comment by cinnamoner** [comment]
@Elbullazul @brandleesee Hey, okay. Would have been nice to be like in Windows though. I'll give the folders a different color and then the glow won't be that annoying.
@Elbullazul What about the hover-ghost effect from settings shown upstream? Was that built in the theme on purpose? And is it bossible to make the background a milder white?

**Comment by Elbullazul** [comment]
@cinnamoner embedded into GNOME

**Comment by feren** [comment]
I THOUGHT SO...
