### ISSUE TITLE
Lock screen shows a grey background instead of desktop background

### ISSUE THREAD

**Issue by karelian** [B00merang-Project/Windows-10#64]
With other themes for **Controls** like Adwaita and Mint-X-Blue, the lock screen displays a faded version of the desktop background. However when I use Windows 10 Light as the **Controls theme**, the lock screen (cinnamon-screensaver I think) becomes a dull grey color and doesn't show any picture.

The clock and the login prompt work normally despite the grey background. Having Windows 10 Light as the Desktop and Window Borders theme has no effect on the matter. The problem only occurs when it's selected as the theme for Controls. Or is this intended behavior?

I've tried with the newest version of the theme (downloaded from your releases page with the filename Windows.10.Light.v0.9.9.SP1.tar.gz). Cinnamon is version 3.0.6.

**Comment by Elbullazul** [comment]
thanks for your feedback

I've noticed this behaviour too, but thought it was due to a lightdm bug (I'm not using mint)

I think that by doing some minor changes I can fix this.

I'll post updates very soon

**Comment by Elbullazul** [comment]
try adding the following lines in gtk-3.0/apps/lightdm-gtk-greeter.css

```css
 * {
	background-color: transparent;
}
```

**Comment by karelian** [comment]
That did the trick. Thanks!

**Comment by Elbullazul** [comment]
glad it works :) will integrate in future releases

**Comment by feren** [comment]
This bug would also affect LightDM GTK Greeter before it was fixed...
