### ISSUE TITLE
Windows 10 Light Theme on Ubuntu GNOME (devel branch)

### ISSUE THREAD

**Issue by brandleesee** [B00merang-Project/Windows-10#65]
## Blurred font in light theme

![screenshot from 2016-10-11 14-03-01](https://cloud.githubusercontent.com/assets/12674437/19269694/60c1aeaa-8fbc-11e6-9f10-61234939f4dd.png)
**specifically 'rename'**

![screenshot from 2016-10-11 14-03-34](https://cloud.githubusercontent.com/assets/12674437/19269695/60c8a228-8fbc-11e6-998b-331b046d8d11.png)

![screenshot from 2016-10-11 14-08-32](https://cloud.githubusercontent.com/assets/12674437/19269696/60d1c9e8-8fbc-11e6-8e9b-783d139fdcbc.png)
## Global Dark Theme

Is it intentional that the GDT ON goes directly to the Dark Black theme?
(I am asking just to check that it is no bug because I prefer it as it is, going directly to DB.)

![screenshot from 2016-10-11 14-13-51](https://cloud.githubusercontent.com/assets/12674437/19269844/0204c432-8fbd-11e6-8a9f-f3a0540f88d3.png)

![screenshot from 2016-10-11 14-14-06](https://cloud.githubusercontent.com/assets/12674437/19269845/020f1342-8fbd-11e6-9ed3-bdf4ea15efdd.png)

**Comment by Elbullazul** [comment]
yes, it's intentional for the dark theme to be all-black

the other issue will be easily dealt with when I get the time to fix it
