### ISSUE TITLE
Windows 10 Icons - Suggestions & Issues

### ISSUE THREAD

**Issue by brandleesee** [B00merang-Project/Windows-10#66]
_extracted from here:_ https://github.com/B00merang-Project/macOS-Sierra/issues/13

Theme used: macOS
Icon pack used: [Windows.10.Icons.v0.5.tar.gz](https://github.com/B00merang-Project/Windows-10/releases/download/v0.9.9-AU/Windows.10.Icons.v0.5.tar.gz) from Win 10 releases [page](https://github.com/B00merang-Project/Windows-10/releases).

Further info from @Elbullazul :

> white icons are because windows 10 icon pack doesn't have symbolic icons, so they're all white. 

![screenshot from 2016-10-11 08-44-25](https://cloud.githubusercontent.com/assets/12674437/19261125/54c0604c-8f8f-11e6-9cce-1e4d5464b90a.png)
**are the white buttons coloured white intentionally? (top left corner)**

![screenshot from 2016-10-11 08-44-36](https://cloud.githubusercontent.com/assets/12674437/19261126/54c6f2cc-8f8f-11e6-85b8-837a865beeaf.png)

**Comment by Elbullazul** [comment]
sorry, I meant post the suggestion here: #49 

it's to keep the repo clean

**Comment by brandleesee** [comment]
@Elbullazul can you please re-open this because I have some issues I want to place here, cheers!

**Comment by Elbullazul** [comment]
@brandleesee what happened?

**Comment by brandleesee** [comment]
I finally got around to properly explain and expand my argument. I did not want to create another issue thread so thought of using this same thread. This is why I asked you to reopen this. Here it goes. 

### Enhancement Suggestion

I'll be straight here: I am unable to design and produce the following icons myself.

The backstory is this: I was organising files and folders and while doing so flared an idea to enhance B00merang Windows 10 Icons with custom icons, therefore, icons which are not in the original Windows/Microsoft suite.

Some icons I would include are for: 

- Games
- Films/Mvies
- Serieses
- Scripts (icon for a folder dedicated to scripts)
- Archives (not the .7z, .zip etc but sort of a generic folder icon)
- *more to follow if this suggestion is accepted*

Note that in the following screenshot I placed some folders in the left vertical panel. To further contribute to my argument, you can see that (example) Pictures has the same icon in said panel and in `$HOME` directory. Thus, I am proposing the same thing for (example) Games and the others. Of course, these icons will be auto-converted if in `$HOME` someone creates (example) the Games folder and the folder's icon is automatically converted from the common folder icon to the *new* icon.

![screenshot from 2017-01-17 11-56-05](https://cloud.githubusercontent.com/assets/12674437/22017847/35f5cdcc-dcac-11e6-80ec-222301431a1b.png)

Here one might include that besides folder icons the suite could have specific icons for Videos/Music/Pictures/Games etc. 

If there is any way I can further explain or add to the argument or even help contribute (although I suck at .svg) I will be happy to oblige.

**Comment by Elbullazul** [comment]
@brandleesee mmm, I don't see a vertical left panel on the screenshot, mind putting it in evidence please?

**Comment by brandleesee** [comment]
You're right, it's just me not being clear and not using the appropriate nomenclature, sorry!

![screenshot from 2017-01-17 11-56-05edit](https://cloud.githubusercontent.com/assets/12674437/22025717/d3a440ae-dcce-11e6-8851-7f5183803953.png)

**Comment by brandleesee** [comment]
This image better illustrates my suggestion.

![screenshot from 2017-01-17 11-56-05edit](https://cloud.githubusercontent.com/assets/12674437/22032123/6941eddc-dce3-11e6-8bff-8d71d829827f.png)

**Comment by Elbullazul** [comment]
oh, now I get it. I should investigate if gnome really does support this, cause home pictures & "default" folders are the ones who get normal support for this feature.
