### ISSUE TITLE
My DNS resolution issue in Xenial

### ISSUE THREAD

**Issue by cinnamoner** [B00merang-Project/Windows-10#68]
@MichaelTunnell
@Bigdaddyontech
@bluedxca93 
@Elbullazul 
@feren 

Fix no. 1

sudo rm /etc/resolv.conf
sudo ln -s ../run/resolvconf/resolv.conf /etc/resolv.conf
sudo resolvconf -u
***
Fix no. 2

sudo mkdir -p /run/resolvconf/interface
sudo resolvconf -u
sudo service resolvconf restart

The fixes are from here:
http://unix.stackexchange.com/questions/280264/no-dns-resolution-after-upgrade-from-ubuntu-14-04-to-16-04

I'm not sure about the first one cause I haven't tried it yet but the 2nd worked like a charm. 

Trusty worked no problem (reinstalled Mint 17.2 and .3) but I was getting nowhere with Xenial (the updates wouldn't fetch, webpages wouldn't load, couldn't install any packages via software centre, synaptic or sudo). Upon applying fix no. 2, everything works. Everything. Even did an upgrade from Neon 7.x.x to 5.8.3 and was successful. Webpages load. Can install packages in every way I want.
***
I'm  just not sure those commands are safe or not. Please tell me your opinion. Thank you.

@feren Please. This also means I can use Feren OS. But I want some opinions first.
@Elbullazul This is an exceptional situation. Please bear with me. Thank you.

**Comment by cinnamoner** [comment]
Kill me but I won't trade Plasma for Cinnamon. Plasma 5.8.3 is ... I'm satisfied. Yeah.

**Comment by cinnamoner** [comment]
Plasma 5.8.3 works just as decently as Cinnamon on a 7 years old machine. So the blabla about Plasma being heavy is just that, blabla.

**Comment by bluedxca93** [comment]
@cinnamoner.

etc resolv.conf is also important for live cd creation. if you modify
it wrong network gets eventually disabled until you fix it and your
way looks like it works.

**Comment by bluedxca93** [comment]
@cinnamoner plasma itself is leightweight. the Problem are some kde
apps, but its possible that it gets better soon.

**Comment by feren** [comment]
Not quite sure here, I'd say to just rename the files, and then see how the OS reacts to it, if it reacts badly, rename 'em back as Root

**Comment by cinnamoner** [comment]
@bluedxca93 Thank you. Yeah. Everything seems to work now on Xenial. Still, on Windows resolution time seems shorter. I don't know. I guess on Windows the tracking mechanisms are better. Seems like  Canonical is monitoring traffic. So does Mint. Mint whipped out Google's engine because Google is not willing to share a bit of revenue with Mint. Popular distros are made by businessmen and Clem is a businessman. This time round he went too far. Hey, I don't nourish illusions.

**Comment by cinnamoner** [comment]
As far as known in the Windows ecosystem there's IPv6 with IPv4 fallbaback. I don't know how it works in Linux. At any rate the network LED is continuously on whilst in with Windows it ain't so.

**Comment by cinnamoner** [comment]
But at least (read upstream which method I've applied) Neon works. It kinda resembles Windows 10. Just slightly. I don't want to discuss who copied who again. Neon has good looks.
***
I didn't know Xenial is guesswork :) On the occasion of reinstalling Mint Cinnamon 17.3, I noticed annoying flickering  (just for a very short time). On 17.2 there's no flickering.

**Comment by bluedxca93** [comment]
hi,
yes. that is possibly due to 17.3 cinnamon version or plymouth themes.
searching possible reasons its a too complex discussion for a small
bug.

**Comment by cinnamoner** [comment]
I need a tracker that blocks other trackers. AOS does such a nice job on Windows. Yeah it's a tracker in its own right but keeps concurrent tracking away.

**Comment by cinnamoner** [comment]
Probably Xfce is the best compromise DEwise. Let's get real, Linux distros can't compare with Windows but they are pretty cool.

**Comment by cinnamoner** [comment]
@Elbullazul I'm closing now but still waiting for the guys to drop in for an opinion on my DNS resolution thing.

**Comment by cinnamoner** [comment]
Yeah, even Discover works pretty good. I'd say it's en early beta phase. Those images representing the apps are really low-res but it's shaping up nicely. Promising. Nice SC.

**Comment by cinnamoner** [comment]
@bluedxca93 @feren Thanks.

**Comment by cinnamoner** [comment]
I've got to reinstall. I'm trying to achieve reproducibility. It kinda shows it's not produced by a multi-billion corporation. For what it is I'd say it's pretty good. Kudos to Jonathan and the guys. Wow. The default wallpaper gave me a headache.

**Comment by cinnamoner** [comment]
On the others hand W10 doesn't show it's produced by a multi ... Sorry.

**Comment by cinnamoner** [comment]
Mark my words. I need things that work now. Not years from now. Today I've achieved some progress though. Let's call it a day. Oh yeah, and I don't want to experiment much longer. I've got things to do and places to go. Cheers.

**Comment by cinnamoner** [comment]
Preliminary conclusions:
1. Probably not a hardware issue.
2. Probably not an ISP issue 
3. Xenial is so and so
4. Neon is getting better (half way through).

**Comment by cinnamoner** [comment]
http://askubuntu.com/questions/622470/dns-probe-finished-bad-config-error-in-ubuntu-14-04/622493#622493
http://unix.stackexchange.com/questions/280264/no-dns-resolution-after-upgrade-from-ubuntu-14-04-to-16-04

One of those. Stay tunned.

**Comment by cinnamoner** [comment]
Just as Brandon finally got his "ideal" Gnome Shell, I'm pretty close to my "ideal" Plasma desktop with the dash (hahaha). Looks Gnomish but I don't need the mouse. WPS is already installed. Few more and ready to go. Will probably never use Discover (not efficient for deploying software). So all in all, I'm pleased. Can't beat Neon.

**Comment by cinnamoner** [comment]
Just checked back. Complete silence.

**Comment by cinnamoner** [comment]
@MichaelTunnell @Bigdaddyontech If you have a little time feel free to jump in and opinionate. I'm chiefly interested in the DNS resolution issue than anything else. Counted as many as 3 fixes. Please consult provided links. Than you.

**Comment by BigDaddyonTech** [comment]
@cinnamoner Not trying to ignore you just trying to respect the decision that was already made to use this forum for the project. email or google+ and I will do what I can to help

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by feren** [comment]
Err, you're spamming the same comment!

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by feren** [comment]
YOU CAN STOP NOW!

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by feren** [comment]
Or did you just hit Post too many times?

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by feren** [comment]
*SIGH*

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by feren** [comment]
Sorry about this, but, this is going too far... No offense, time to refresh and delete the duplicate comments from oldest > second newest

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by feren** [comment]
Sigh, not even that's working... Time to lock it for a couple of seconds...

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by cinnamoner** [comment]
@BigDaddyontech @MichaelTunnell Fair enough. rich.addison2@gmail.com Thanks. Finally I'm getting somewhere. Thank you guys.
***
@Elbullazul Thank you. No more threads dealing with issues that don't belong. Really and period.

**Comment by feren** [comment]
*sigh* Time for clean up, like I said, deleting Oldest > 2nd Newest

**Comment by feren** [comment]
@cinnamoner Ah oops, sorry about that, didn't mean to delete the last one, GitHub didn't update... Sorry...

**Comment by feren** [comment]
@cinnamoner So, have you resolved it?

**Comment by cinnamoner** [comment]
@BigDaddyonTech @MichaelTunnell @feren Sorry. rich.addison2@gmail.com

**Comment by feren** [comment]
It's ok, sorry on my part, (GitHub didn't help by not showing the comments deleting)

**Comment by feren** [comment]
@cinnamoner Off Topic: Also, what d'ya think? feren OS 2017.0 (Development has not started yet) with its possible new wallpaper:
![screenshot from 2016-11-06 15-11-37](https://cloud.githubusercontent.com/assets/11057934/20039445/01810820-a43c-11e6-8881-fff56cd7360c.png)

**Comment by Elbullazul** [comment]
@cinnamoner I suggest that for the next issue you want to open, create an empty repo called "discussion" and we talk there, ok? 

if not, i'll make it myself

**Comment by Elbullazul** [comment]
nevermind, it's here:https://github.com/Elbullazul/Discussion/issues/1

**Comment by feren** [comment]
@Elbullazul What happened to the discussion repository?

**Comment by Elbullazul** [comment]
deleted because of nonsense

I wasn't shure I wanted to do it and some other user kind of convinced me to remove it

**Comment by Elbullazul** [comment]
wich there was a huge "DELETE" button sometimes...

**Comment by cinnamoner** [comment]
.

**Comment by cinnamoner** [comment]
:) Okay. No more off stuff.
