### ISSUE TITLE
Cinnamon text colors are messed up in the latest release of cinnamon with the git version of the project

### ISSUE THREAD

**Issue by fpqc** [B00merang-Project/Windows-10#69]
Hi, I'm using the latest version of the project directly from a github clone on the latest version of cinnamon.  The text colors are all messed up, namely they are dark on dark.  Any suggestions?

**Comment by Elbullazul** [comment]
hi, please include a screen shot to Illustrate the bug

**Comment by fpqc** [comment]
![screenshot from 2016-11-23 18-59-21](https://cloud.githubusercontent.com/assets/6083371/20582421/178e5214-b1af-11e6-8342-84b0d2035900.png)

**Comment by Elbullazul** [comment]
Sorry, our theme is not yet available for cinnamon 3,2 because we haven't had time to test it on the newest cinnamon build.

**Comment by fpqc** [comment]
@Elbullazul If I can help in any way let me know.  Thanks!

**Comment by feren** [comment]
@fpqc Related Issue: https://github.com/Elbullazul/Redmond-Themes/issues/15
The easiest fix (until Cinnamon on PPAs gets the Pull Request to restore unique menus):
In THEME-DIR/cinnamon/cinnamon.css:
1. Find 'popup-menu'
2. Copy all of the tag inside of it
3. Paste it above
4. Change the tag on the pasted settings to 'menu'

**Comment by fpqc** [comment]
Heya, I switched the git branch to testing and now the Menu works.  

The only thing that looks weird now is the text-color:

![screenshot from 2016-12-07 18-45-09](https://cloud.githubusercontent.com/assets/6083371/20991602/5ec93e6a-bcad-11e6-81f2-36729d82ddff.png)

By the way, is there any new version of that old menu applet that looked so cool.  The old one in the screenshots doesn't seem to work with cinnamon anymore.

**Comment by Elbullazul** [comment]
@fpqc the menu applet you talk about has been discontinued (I guess by seeing the latest commits are from 2 years from now). For now, maybe I can talk to a dev I know to adapt the configurable menu for 3.2, and then I may be able to create a new layout looking like the one in slingshot.

haven't tried this, but I guess that by adding
```css
color: white;
```
to the 
```css
.window-list-item-box {
```
class, text should go back to white.

**Comment by feren** [comment]
@fpqc Which menu was that? Looks like Cinnamon Menu

**Comment by fpqc** [comment]
@feren Huh? It is the cinnamon menu, but it is using the Win10 theme if you are on the testing branch of this repo.

**Comment by Elbullazul** [comment]
@fpqc did it work?

**Comment by fpqc** [comment]
@Elbullazul Sorry I haven't had an opportunity to test yet. Hopefully later today.

**Comment by fpqc** [comment]
@Elbullazul Yep. Adding that little piece in cinnamon.css fixed it all up.

**Comment by Elbullazul** [comment]
@fpqc agreed, it would be easier. However, I don't want to split up the theme in 2 repos, so maybe I'll add a couple new branches
-> Windows 10 Dark
-> Windows 10 Light
-> Windows 10 Dark (testing)
-> Windows 10 Dark (testing

**Comment by fpqc** [comment]
Thanks!
