### ISSUE TITLE
Cinnamon panel tiny steam icon.

### ISSUE THREAD

**Issue by Zerophase** [B00merang-Project/Windows-10#70]
On the latest Rolling release build, the Steam icon shrinks for some reason, while all of the other icons don't change sizes as drastically.

Arc Dark:
![screenshot_1480661394](https://cloud.githubusercontent.com/assets/4284284/20825458/d2835d8c-b829-11e6-8638-f8eaa8ca3c82.png)

Windows 10:
![screenshot_1480661453](https://cloud.githubusercontent.com/assets/4284284/20825460/d79df37c-b829-11e6-8cf6-eacbbd01919a.png)

**Comment by Elbullazul** [comment]
thanks @Zerophase , I'll check this bug as soon as possible

**Comment by Elbullazul** [comment]
@Zerophase does this still happen? I think I reduced padding in panel...

**Comment by Zerophase** [comment]
I don't believe the release branch has been updated. When I get the chance I'll try installing master.

**Comment by Elbullazul** [comment]
seems to have disappeared
