### ISSUE TITLE
Metacity - Latest Update Moved Window Text To The Left

### ISSUE THREAD

**Issue by annoyingduck** [B00merang-Project/Windows-10#72]
Previous releases had the window text centered, the latest update moved it to the left side. I'm using Cinnamon with Metacity-standard and XFCE with Compiz/GTK/Metacity, result is the same on both. I prefer it centered, but not sure if this is the new direction you are headed.  Tried adding some spacers in dconf-settings, but that just made the Window frame disappear entirely.

**Comment by Elbullazul** [comment]
@annoyingduck windows has been using left-aligned text since windows 95.
if you want the centered text again, i can give instructions. It's easily doable, just need to swap a couple of lines

**Comment by annoyingduck** [comment]
@Elbullazul Yes that would be great if you could let me know how to do that.  Thanks

**Comment by Elbullazul** [comment]
here you go: 
```xml
<draw_ops name="title-text-focused">
<title color="#878787" x="(0 `max` (width-title_width-mini_icon_width-IconTitleSpacing)) / 2 + mini_icon_width + IconTitleSpacing" y="(height - title_height) / 2"/>
</draw_ops>

<draw_ops name="title-text-unfocused">
<title color="#cfcfcf" x="(0 `max` (width-title_width-mini_icon_width-IconTitleSpacing)) / 2 + mini_icon_width + IconTitleSpacing" y="(height - title_height) / 2"/>
</draw_ops>
```

just change the hex color values for the light theme, if you need.

**Comment by annoyingduck** [comment]
@Elbullazul Thank you, that worked perfectly.  Not only the centering, but changing the text color is a great option too.  I never edited a theme before.  One other quick question:  How can I re-label the theme so that in my theme selector I can have 2 versions - your original (ex: Windows10) and then have another entry for my edited one (ex: Windows10-Centered)?  Would just renaming the file do that or is there a line of code that needs to be changed to actually change how the theme label appears in my theme selector?

**Comment by Elbullazul** [comment]
in themes create a new folder named Windows10-Centered, and then copy the metacity folder inside it.
