### ISSUE TITLE
No shutdown/logout icon in the new startup menu

### ISSUE THREAD

**Issue by greenlaw110** [B00merang-Project/Windows-10#73]
Where can I find them from this start menu?
![image](https://cloud.githubusercontent.com/assets/216930/21290360/1549620e-c4f2-11e6-8695-007133a983ae.png)

**Comment by feren** [comment]
There is no Power option by default (unless you use something like feren OS that already comes with shortcuts for power options) so you'll need to use the User Applet, or Shutdown Commands from unity...

**Comment by Elbullazul** [comment]
@greenlaw110 like feren says, there's no shutdown button. and development on this applet stopped, so I'm thinking on adding some code for the option, but it may take some time...

**Comment by feren** [comment]
@Elbullazul Could you also look for a fix to this bug? (It's a BIG Cinnamon Crashing Bug)
https://github.com/jfarthing84/cinnamon-slingshot/issues/8

**Comment by greenlaw110** [comment]
@feren and @Elbullazul  how to explain we have the shutdown button before as shown below:

![image](https://cloud.githubusercontent.com/assets/216930/21340783/b8f7e588-c6c3-11e6-8483-8fef471f64b4.png)

**Comment by Elbullazul** [comment]
you can swtch back to the default menu, just open settings>applets and remove cinnxpstarkmenu & add menu back to the panel

**Comment by feren** [comment]
@greenlaw110 Probably because there's a Shutdown button hard-coded into that menu unlike Slingshot...

**Comment by BigDaddyonTech** [comment]
@feren @Elbullazul 
https://www.youtube.com/watch?v=fHD59Up5-iQ
