### ISSUE TITLE
Doesn't work on Debian Jessie Mate

### ISSUE THREAD

**Issue by frankzen** [B00merang-Project/Windows-10#74]
Downloaded and installed deb package on Debian Jessie. In Mate theme doesn't show up in appearances app. Tried copying into ~/.themes...same result.

**Comment by Elbullazul** [comment]
@frankzen the last time we published a deb file it was a disaster of bad installs, broken themes & incompability in general. Therefore, we strongly suggest you:
1. Clone this repository and link the themes into your .themes folder
2. Download and manually install the original file from the [latest master branch available](https://github.com/B00merang-Project/Windows-10/archive/master.zip)
3. Download and manually install the latest zip file from our [releases page](https://github.com/B00merang-Project/Windows-10/releases) into .themes.

Also, it's possible MATE won't load the theme completely (has happened to us sometimes). If it happens to you, please report it here.

**Comment by mincefriend** [comment]
A similar problem with Mint/Mate 18.1: all zip’s installed manually, but theme doesn’t show up int the theme manager. Is it a Mate issue?

**Comment by Elbullazul** [comment]
@mincefriend maybe, I haven't tried mate for a while now, maybe the latest has some stuff to correct.
