### ISSUE TITLE
Windows 10 Theme in the Wild

### ISSUE THREAD

**Issue by feren** [B00merang-Project/Windows-10#75]
@Elbullazul Just a thread for posting screenshots or snippets, etc of Your Windows 10 Theme in the wild...

**Comment by feren** [comment]
Firstly, this:
https://youtu.be/evF8pCOUdrw?t=3m58s

(Look in Terminal, look familiar?)

**Comment by brandleesee** [comment]
We are sort of endorsed by Tech Pills, however, the screenshot only lists the Win10 'flavours' and not any  actual usage. I haven't checked whether he has uploaded a video reviewing W10.

[W10 on Tech Pills](https://youtu.be/pmRnV_ibIFE?t=9m13s)

**Comment by feren** [comment]
@Elbullazul A freaking awesome looking Cinnamon, and a modification of your Windows 10 Dark Decorations!
https://www.youtube.com/watch?v=gmBhOel64eo

**Comment by cinnamoner** [comment]
@feren I haven't done any research but I think it's been built by the guy who has some W10 stuff on Open Desktop.
***
The installer is well executed. BUT the default mint spinning thing SHOULD be replaced by something different. I'd suggest the one from Plasma. Or something else but not the default mint spinning thing. How does the thing look in the real W10? I don't know cause I don't use that darn OS, unless they open-source it. It could be proprietary and open source, you know. I'm the super user and not C*****a.
