### ISSUE TITLE
Black window menu background on Light Theme on Xfce4

### ISSUE THREAD

**Issue by stsichler** [B00merang-Project/Windows-10#77]
When using the Light Theme on Xfce4 (Mint 18.1 Xfce), the window menus, e.g. of Thunar have a black background.

**Comment by Elbullazul** [comment]
screenshot please?

**Comment by stsichler** [comment]
here comes a screen-shot. sorry for not initially posting it. It is the computer of a friend of mine that I installed Linux Mint on. I do not have access to the computer all the time.

Btw. Not only the background color of the window menu is wrong, but as you can also see in the screenshot, the background color of the notification area down right seems to be wrong, too.

Thanks for your work! I like the theme very much.
![screenshot](https://cloud.githubusercontent.com/assets/6442267/23085689/5ac8dd8a-f569-11e6-89a0-b99820f58ffa.png)

**Comment by Elbullazul** [comment]
have you tried [this release of the theme?](https://github.com/B00merang-Project/Windows-10/archive/master.zip)

**Comment by stsichler** [comment]
No I didn't. I was using 0.9.9 SP1. 
Wow, okay, but you already fixed in master. It is all correct there!
So I close this issue and thank you for your help!

**Comment by Elbullazul** [comment]
@stsichler you're welcome :)
