### ISSUE TITLE
Dark Fonts in Themer using Windows 10 Dark Theme

### ISSUE THREAD

**Issue by swoopa** [B00merang-Project/Windows-10#78]
Inactive fonts within the FerenOS Themer are dark and hardly readable when using the Windows 10 Dark Theme.
![feren-themer](https://cloud.githubusercontent.com/assets/25865515/23093940/a239a14c-f62a-11e6-8f83-e930c64af6a8.png)

**Comment by feren** [comment]
@swoopa Oh yeah, that issue, @Elbullazul I have a feeling this is related to the GTK2 Theme...
Actually wait, let me check if the fonts aren't coded to be black afterwards

**Comment by feren** [comment]
@swoopa Just gonna check if the fonts being black is a coding issue quickly, if so, that'll be fixed in the next build

**Comment by feren** [comment]
@swoopa My bad, the fonts are coded to be black, I'll close this issue, sorry for not realizing @Elbullazul ...

**Comment by feren** [comment]
@swoopa I'll fix this in a build being uploaded tommorow, sorry for coding it black by accident

**Comment by feren** [comment]
@swoopa Yeah, I fixed it and found it is indeed coding in Themer that made it black, sorry about that.

**Comment by feren** [comment]
@swoopa Building and uploading the ISO now, it'll still be 2017.0 Alpha 2 BTW, and sorry for me not noticing that...

**Comment by feren** [comment]
...and yes, I also am a contributor to this theme too... ;D

**Comment by swoopa** [comment]
@feren @Elbullazul Thanks so much for the quick response I'm very impressed, it's Colin by the way Feren, I just downloaded Alpha 1 are you now working on Alpha 2, do I have to re-download or will these updates push through on Alpha 1 ? keep up the great work guys!!

**Comment by feren** [comment]
@swoopa Sadly, I can't get repositories working just yet, so you'll have to re-download Alpha 2...

Tip:
If you use Etcher or something similar, use the 'No ISOHYBRID' ISO, otherwise, use the normal ISO...

**Comment by swoopa** [comment]
@feren Thanks Feren for the info!!
