### ISSUE TITLE
I cant install Windows 10 Light on Lubuntu

### ISSUE THREAD

**Issue by ELDONPUTAS** [B00merang-Project/Windows-10#79]
david@Millos:~/Descargas/TransPack$ bash install.sh
Welcome to the B00merang Theme Installer. For usability support, visit http://b00merang.weebly.com/TransPack.html

Press any key to continue
Internet connection detected. Proceding...
You can apply a Dark or a Light variant of this theme. Both will be installed anyways
Windows 10 Light = 1   Windows 10 Dark = 2 [1]:1
Window manager identified. Proceding with installation
master.zip                    [                              <=>  ]   3,76M   619KB/s    in 6,8s    
windows_x11.zip           100%[==================================>]  16,79K  20,5KB/s    in 0,8s    
mv: no se puede efectuar `stat' sobre 'Windows-10-icons': No existe el archivo o el directorio
Root access is required for a system-wide installation. Please authentify to continue
[sudo] password for david: 
Access acquired. Proceding with installation
mkdir: no se puede crear el directorio «/usr/share/wallpapers/windows-10»: No existe el archivo o el directorio
install.sh: línea 338: cd: GTK/Windows 10 Light: No existe el archivo o el directorio
cp: no se puede efectuar `stat' sobre 'wallpaper.jpg': No existe el archivo o el directorio
install.sh: línea 63: cd: Windows 10 Light: No existe el archivo o el directorio
install.sh: línea 72: cd: ../Windows 10 Dark: No existe el archivo o el directorio
install.sh: línea 383: cd: /home/david/Descargas/TransPack/tmp/GTK/Windows 10 Light: No existe el archivo o el directorio
install.sh: línea 385: cd: ../Windows 10 Dark: No existe el archivo o el directorio
chown: no se puede acceder a '/usr/share/themes/Windows 10 Light': No existe el archivo o el directorio
chown: no se puede acceder a '/usr/share/themes/Windows 10 Dark': No existe el archivo o el directorio
chmod: no se puede acceder a '/usr/share/themes/Windows 10 Light': No existe el archivo o el directorio
chmod: no se puede acceder a '/usr/share/themes/Windows 10 Dark': No existe el archivo o el directorio
cp: no se puede efectuar `stat' sobre 'Windows 10': No existe el archivo o el directorio
chown: no se puede acceder a '/usr/share/icons/Windows 10': No existe el archivo o el directorio
chmod: no se puede acceder a '/usr/share/icons/Windows 10': No existe el archivo o el directorio
Applying changes to lxde
Lxde supports only manual input to change themes. Please do so by opening the corresponding Tweak tool

Removing temporary files...
The theme was successfully installed and applied. Thank you for using our theme installer!
david@Millos:~/Descargas/TransPack$

**Comment by Elbullazul** [comment]
@ELDONPUTAS installer has gone offline because we've been re-arranging our repositories. 

this week we should update a new install script with a simplified structure

**Comment by cinnamoner** [comment]
@Elbullazul I noticed. It'll take a while to get used to the new structure. But seems a good job.

**Comment by Elbullazul** [comment]
@ELDONPUTAS use the new install script: https://github.com/B00merang-Project/Windows-10/releases/tag/Rolling
