### ISSUE TITLE
Wrong menu text colors on Linux Mint 18.1 Serena

### ISSUE THREAD

**Issue by stsichler** [B00merang-Project/Windows-10#80]
Hi,
since I upgraded my Mint 18 to Mint 18.1 (Cinnamon), the menu text colors are wrong (unreadable). Also the text color of inactive windows in the task bar seem wrong. See attached screenshot.
I have installed the rolling release of your theme from today.
![mint 18 1 serena wrong menu text color](https://cloud.githubusercontent.com/assets/6442267/23544894/2b857264-fff9-11e6-8abf-624252a792bc.png)

**Comment by Elbullazul** [comment]
you're lucky, I just installed serena yesterday!

I'll post a fix when I finish setting up the new OS

cheers and thanks for the feedback :)

**Comment by feren** [comment]
@Elbullazul Finally!

**Comment by cinnamoner** [comment]
@Elbullazul Serena? How do you like her? Yet another stone age chick, I guess. Cinnamon is doomed. Gnome and Plasma are getting better.

**Comment by cinnamoner** [comment]
> you're lucky, I just installed serena yesterday!
I'll post a fix when I finish setting up the new OS

Setting up Mint is notoriously hard :) Install, firewall up, update, uninstall/install some apps. Done.

**Comment by Elbullazul** [comment]
@stsichler I don't have the bug, have you tried [this version?](https://github.com/B00merang-Project/Windows-10/archive/master.zip)

**Comment by stsichler** [comment]
Obviously I haven't... I'm sorry. The bug is now gone with this version for me, too. I confused rolling release with master.
