### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by GroumphyOriginal** [B00merang-Project/Windows-10#81]
Hello, 

First, congratulation for this transformation pack and his quality... Great job. 

Second, I'm here to report an issue (sorry :/ ). Indeed. I've download the [Shell-Scripts-masters.zip](https://github.com/B00merang-Project/TransPack/archive/master.zip), where is the install script (install.sh). 

When I execute it, I have the next error: 

> File download failed. Check internet connection

Seem this log message come from a "non-download" of one of the mentioned package in the script: 
`
get_zip() {
  echo "Downloading archives..." | tee -a "$LOG"
  wget https://github.com/B00merang-Project/Windows-10/archive/master.zip -q --show-progress
  wget https://github.com/B00merang-Project/Windows-10/archive/icons.zip -q --show-progress
  wget http://b00merang.weebly.com/uploads/1/6/8/1/16813022/windows_x11.zip -q --show-progress
}
`

After testing the URL, seem the second relation to the icons give the 404 not found error... 

As workaround, and with the ressources available in the /RES/ folder, I've adapted the next variable: 
`testing="no"`
to
`testing=""`

Seem you need to add the correct ressources in the ressources. Can you do that? 
Thanks a lot, regards,

Xavier

**Comment by Elbullazul** [comment]
@GroumphyOriginal the latest script should fix it
