### ISSUE TITLE
multiple errors in transpack.sh + solution

### ISSUE THREAD

**Issue by auipga** [B00merang-Project/Windows-10#82]
within the main function:
`# get_files` -> `get_files`  should not be disabled but is commented out

usage of download function within get_files:
`download http://b00merang.weebly.com/uploads/1/6/8/1/16813022/windows_x11.zip ...` download() expects downloaded file to be `master.zip` but it is not. Renaming fails, so does unzipping.
change mv command to `mv ${1##*/} $2`

Detecting gnome fails using Arch Linux with latest gnome and running transpack.sh using zsh.

**Comment by auipga** [comment]
It also depends on netcat which is not mentioned. Without netcat the online test always returns that I'm offline ;)

**Comment by Elbullazul** [comment]
@auipga new release should fix this. BTW what's the output of your DE on arch? I didn't know the script used netcat. I'll add it to the readme later.

thanks for your feedback :)

**Comment by auipga** [comment]
to find the usage of netcat [Ctrl]+[F] `nc github.com`

`detect_wm` function uses `xprop` which isn't installed on my machine. With `xorg-xprop` installed the output is `GNOME Shell`

**Comment by Elbullazul** [comment]
@auipga all right, I'll add a check_dependencies function so it won't happen again

thanks for your feedback

**Comment by GroumphyOriginal** [comment]
With those comments, can you upload a latest updated? I will try on specifics machine. 
Thanks for your feedback. 
Xavier

**Comment by Elbullazul** [comment]
@GroumphyOriginal which latest?

**Comment by GroumphyOriginal** [comment]
The correction of @auipga ... 
Or this is done? 

For your information, [I 've created a repository for my suggestion](https://github.com/GroumphyOriginal/W10TPack)... Than, you can direct branch those in the master if you want.

**Comment by Elbullazul** [comment]
@GroumphyOriginal I rewrote the whole thing from scratch. It now has automatic file detection name for downloaded files for renaming them, check_dependeincies (xprop & netcat) and an offline installation mode (no netcat needed)

here's the latest version: https://github.com/B00merang-Project/Shell-Scripts/blob/master/transpack.sh

**Comment by GroumphyOriginal** [comment]
Thanks. I will test. If I found an incident I will declare it here.
