### ISSUE TITLE
[Suggestion] Some idea

### ISSUE THREAD

**Issue by GroumphyOriginal** [B00merang-Project/Windows-10#83]
Hi,

I'm occupied to transform a Linux Mint (Cinnamon desktop) in a "Windows style" for someone of my family (... not so IT minded than a classical people and very "Redmond orientied"). 
To finish this specifics installation, after the 'install.sh', I have make the next manipulation:

### A. Libre Office 5.x customization
Note: this is fully describe on [this website](http://www.linuxslaves.com/2015/12/download-miscosoft-office2013-theme-for-libreoffice-to-make-libreoffice-look-like-ms-office2013.html).

1. on all great public distros 's installed LibreOffice (like Ubuntu, Mint, ...); why not use an specific theme for this applications too? Some people have make the necessary. 
1.1. first step is to download the ressources:
Seem we can add in the function `get_zip()` the next command: 
(idea: inclue those ressources in your repository?)
Note this is also describe [on this page](http://charliecnr.deviantart.com/art/Office-2013-theme-for-LibreOffice-512127527).
```
wget http://www.deviantart.com/download/512127527/office_2013_theme_for_libreoffice_by_charliecnr-d8gwo4n.zip?token=ea7967a65f9d0b5246504329dcf65bbf12a21328&ts=1489925060 -q --show-progress
 ```
1.2. next we need to rename the archive file with the next name: 
```
sudo mv office_2013_theme_for_libreoffice_by_charliecnr-d8gwo4n images_office2013.zip```
(idea: if you rename it with the same name as the original theme name you don't need to customize at the boot of Libre Office)
```
1.3. next we move the archive file to 2 locations: 
```
sudo cp -i images_office2013.zip /usr/lib/libreoffice/share/config/
sudo cp -i images_office2013.zip /usr/share/libreoffice/share/config/
```
1.4. get the splash screen for Libre Office, again modify the 'get_zip()' function with the next command: 
```
wget http://www.mediafire.com/download/ln6769asyb87187/flat_logo.svg -q --show-progress
wget http://www.mediafire.com/download/2ld584b8kgo57m1/intro.png -q --show-progress
```
1.4.1. we backup the current file: 
```
cd /usr/lib/libreoffice/program/
sudo mv flat_logo.svg old_flat_logo.svg #or other name?
sudo mv intro.png old_intro.png #or other name?
```
1.4.2. copy of the new splashscreen:
```
sudo cp [download_path]/flat_logo.svg flat_logo.svg
sudo cp [download_path]/intro.png /usr/lib/libreoffice/program/intro.png
```
### B. Custom bootsplash
_**Edit: tested 03 21 17 -> doesn't function on my computer :(**_ 
(Note: I don't have tested this part!)
Note: this is describe [on the next page](http://ask.xmodulo.com/change-boot-splash-screen-ubuntu-linux-mint.html).
For the custom boot splash, seem this is scriptable too. 
First choose a custom bootscreen on [Gnome-Look](https://www.gnome-look.org/browse/cat/108/). But some [Windows 10 bootscreen seem available too](https://www.gnome-look.org/content/show.php/Windows+10+bootsplash?content=174351)! (And your project seem in the discussion!)
After this we need to choose the theme: 
1. copy the theme in the Plymouth
```
sudo cp -r Win10BootScreen/ /lib/plymouth/themes/
sudo update-alternatives --install /lib/plymouth/themes/default.plymouth default.plymouth /lib/plymouth/themes/Win10BootScreen/Win10BootScreen.plymouth 100
```
2. make a choice on the right Plymouth theme:
```sudo update-alternatives --config default.plymouth```
(this need a choice of the user)
2.1. confirm the choice by recompiling: 
```sudo update-initramfs -u```

An extended documentation is also available [on the Linux community page](https://community.linuxmint.com/tutorial/view/1149).

Edit: 25 03 2017
### C. Customize the background
The background after the personification stay the "original" background. 
Like this [tutorial](http://www.noobslab.com/2017/01/do-you-like-windows-10-look-but-love.html). 

Can this part integrated in the Transformation pack? 
Or this is an specific, sided, project/repository? 

Best regards,

Xavier

**Comment by Elbullazul** [comment]
@GroumphyOriginal thanks for the suggestions. The libreoffice seems interesting. The plymouth is harder because the format changed for yakkety and it may break and have no bootsplash at all. I'll check if it still runs OK and then post an answer

**Comment by GroumphyOriginal** [comment]
Hi, 

Not a problem. If you need some idea... :D As user of your solution, this is easy for me.

### For Plymouth in Ubuntu Yakkety
If you need a tool, you have [Plymouth Manager](http://www.ubuntugeek.com/plymouth-manager-simple-tool-to-change-splash-screen-themes.html).
Easy to use, you can copy file and analyze the traffic on your hard drive no? (Sorry, always not yet tested...)

### For others Ubuntu versions
You can try this method (I'll try to test ASAP). 

If you need others idea, I'm full :P 

Regards,

**Comment by GroumphyOriginal** [comment]
Hi, 

Another tips, but only for debugging, seem we can try to add two functions: 
```
	#Log and echo 
	Eko() { echo $2
			Log "$1 : $2" }
	Log() { "$1" >> "$LOG"}
```
Then, in place to use a line like: 
```
echo "Something went wrong while installing: $isok. Aborting..." | tee -a "$LOG"
```
You can use:
``` 
Eko "$LINENO" "Something went wrong while installing: $isok. Aborting..."
```
Only the right message will be print on the screen, but in the log file you have the line numbering. 
To use it only in a debut method, you can use the next: 
```
Eko "$LINENO" "" #Message is empty, second variable is not "used"
```
More easily for the developers. (heu for me I don't known if this can be useful for you)

Regards,

**Comment by Elbullazul** [comment]
@GroumphyOriginal good idea! implementing soon...

**Comment by GroumphyOriginal** [comment]
(Be careful, I'm not a specialist in Shell script, syntax need to be verified)

**Comment by cinnamoner** [comment]
> A. Libre Office 5.x customization

@GroumphyOriginal Why not WPS Office for Linux? Looks pretty much like an MS Office clone to me. Ribbon UI 'n all.

**Comment by cinnamoner** [comment]
> because most people use libreoffice

@Elbullazul I'm speechless. Really.

**Comment by GroumphyOriginal** [comment]
(I 've received some mails with a discussion... But I cannot find here the discussion... And 'll answer on the received mail)

@cinnamoner > if I've quoted the LibreOffice, this is not by choice or by preference, etc. Reason is very simple: this is installed by default... This is not my preferred Office application but as said by @Elbullazul this is one of the most used Office application. 
And for sample, in this case, this is one of the most easier to personalize. 
If you want to personalize your preferred Office application, why not fork this project and propose a conditional structure of detection (if your preferred Office application is installed)?

@Elbullazul > I 've tested the Plymouth personnalisation, in relationship with the bootscreen, this doesn't functions :/ I will check something with real possibilities. Than, forgot this part. 

Regards,

**Comment by cinnamoner** [comment]
@GroumphyOriginal Okay. I now understand what you mean. I was merely trying to help with a suggestion. Here it is again. http://wps-community.org/downloads

![women_in_dance_spellcheck](https://cloud.githubusercontent.com/assets/15638605/24173670/a3b7b260-0e95-11e7-8b31-7e4d62fdab84.png)
![presentation_slide2](https://cloud.githubusercontent.com/assets/15638605/24173679/acd7be30-0e95-11e7-8ec6-c63265a71818.png)
![spreadsheets_screenshot_arial](https://cloud.githubusercontent.com/assets/15638605/24173691/b978faaa-0e95-11e7-9c67-5cfed8d04e1f.png)

> because most people use libreoffice.

@Elbullazul Statistically inaccurate statatement. But hey, I'm not perfect either. Hahaha! 😄😄😄

**Comment by cinnamoner** [comment]
@GroumphyOriginal Good luck and all my best wishes to you.

Kind regards,
Richard

**Comment by GroumphyOriginal** [comment]
For information I have add an suggestion in the main topics (C. background -> adapt it :) )
