### ISSUE TITLE
[Bug] No "Windows" icon for the menu

### ISSUE THREAD

**Issue by GroumphyOriginal** [B00merang-Project/Windows-10#84]
Hellloo!

Sorry, but I have found a bug again... 
Seem the system menu is not adapted by the themes or script. 
This stay the Linux Mint Logo with the text "Menu". 

Workaround: 
- Click with the right button of your mouse on the menu, 
- Choose Configure
- Select in the appearance zone "Use a personalized icon" 
- in the path encode: /usr/share/theme/Windows 10 Light (or other)/cinnamon (or other)/menu.png (or others)

Have a nice day :) 

Xavier

**Comment by Elbullazul** [comment]
@GroumphyOriginal ah? it's supposed to be automatic now

anyways, thanks for posring

**Comment by feren** [comment]
@Elbullazul Linux Mint overrides it for some reason in it's Menu Applet Icon

**Comment by cinnamoner** [comment]
Then override mint's override. Blah.

**Comment by GroumphyOriginal** [comment]
You're right. :) Thanks for your comments.
