### ISSUE TITLE
[Important] MDM could be deprecated by 2021

### ISSUE THREAD

**Issue by feren** [B00merang-Project/Windows-10#85]
If Linux Mint decides they want to switch to LightDM in 18.2...

> In the scope of Mint 18, that means we’re committed to supporting MDM on that package base until 2021.

Suggestions:
- Convert the MDM theme to a LightDM WebKit Greeter Theme

**Comment by feren** [comment]
Affects: Windows 10 MDM

**Comment by Elbullazul** [comment]
@feren I have no idea how to edit a lightdm WG theme. And I don't have nothing to test it with.

in fact, we don't even support the login themes anymore

**Comment by feren** [comment]
@Elbullazul Oh ok, it's just that you know, you had the Login Screens on your website directly...
