### ISSUE TITLE
Theme parsing error in gtk-3.0/apps/xfce.css

### ISSUE THREAD

**Issue by stsichler** [B00merang-Project/Windows-10#86]
On XFCE, I get:
Gtk-WARNING **: Theme parsing error: xfce.css:17:22: Not a valid image

What is instead correct here? "background-image: none;" ?

Thank you!

**Comment by Elbullazul** [comment]
@stsichler it was bad syntax on a background-image line

I just issued a fix

**Comment by stsichler** [comment]
thank you!
