### ISSUE TITLE
[Slingshot Bug] The Themer Bug I Have No Idea What To Name

### ISSUE THREAD

**Issue by feren** [B00merang-Project/Windows-10#88]
**There was no issues panel on Slingshot, so I'll post it here**
There's been a bug in Slingshot for a while now, where if the Themer script for any theme that uses Zuro UI Menu/Slingshot (e.g: the one below) is run, at random times, the Applet seems to become prematurely initialised, and like this:
![screenshot from 2017-04-15 11-24-32](https://cloud.githubusercontent.com/assets/11057934/25062943/d10a84f8-21ce-11e7-94a0-3985395074b0.png)

What this bug is capable of doing:

- Crashing Cinnamon (Applet is larger than screen) depending on the theme used when hovered over

Important things to know:

- The applet is still working fine, but it's off-screen
- CinnVIIStarkMenu works just fine in the same circumstances

Script:
```
#!/bin/bash
gsettings set org.gnome.desktop.interface gtk-theme 'Chrome OS'
gsettings set org.gnome.desktop.wm.preferences theme 'Chrome OS'
gsettings set org.gnome.desktop.interface icon-theme 'Paper'
gsettings set org.cinnamon.theme name 'Chrome OS'
gsettings set org.cinnamon.desktop.wm.preferences theme 'Chrome OS' 
gsettings set org.cinnamon.desktop.interface gtk-theme 'Chrome OS'
gsettings set org.cinnamon.desktop.interface icon-theme 'Paper'
gsettings set org.gnome.shell.overrides button-layout menu:minimize,maximize,close
gsettings set org.gnome.desktop.wm.preferences button-layout menu:minimize,maximize,close
gsettings set org.cinnamon.desktop.wm.preferences button-layout menu:minimize,maximize,close
gsettings set org.cinnamon.muffin button-layout menu:minimize,maximize,close
gsettings set org.cinnamon.desktop.interface gtk-decoration-layout menu:minimize,maximize,close
killall docky
rm ~/.config/autostart/docky.desktop
gsettings set org.cinnamon panels-height "['1:38', '2:38']"
gsettings set org.cinnamon enabled-extensions "['!Flipper@connerdev', 'transparent-panels@germanfr']"
gsettings set org.cinnamon panels-enabled "['1:0:bottom']"
gsettings set org.cinnamon panels-resizable "['1:false', '2:false']"
gsettings set org.cinnamon enabled-applets "['panel1:left:0:slingshot@elbullazul:47', 'panel1:left:1:IcingTaskManager@json:44', 'panel1:right:0:keyboard@cinnamon.org:7', 'panel1:right:14:user@cinnamon.org:48', 'panel1:right:4:ScreenShot+RecordDesktop@tech71:52', 'panel1:right:5:removable-drives@cinnamon.org:6', 'panel1:right:6:weather@mockturtl:43', 'panel1:right:7:MessagingMenuV3@blub:23', 'panel1:right:8:systray@cinnamon.org:36', 'panel1:right:9:network@cinnamon.org:9', 'panel1:right:10:sound@cinnamon.org:10', 'panel1:right:11:power@cinnamon.org:11', 'panel1:right:12:notifications@cinnamon.org:4', 'panel1:right:13:calendar@cinnamon.org:128']"
gsettings set org.nemo.window-state start-with-menu-bar false
gsettings set org.cinnamon.desktop.interface cursor-theme 'DMZ-Black'
NEWFILE='/usr/share/feren-os/logos/Logo white.png'
OLDFILE='/usr/share/feren-os/logos/blank.png'
for filename in ~/.cinnamon/configs/slingshot@elbullazul/*.json; do
    for ((i=0; i<=0; i++)); do
        sed -i "s~$OLDFILE~$NEWFILE~g" "$filename"
    done
done
NEWFILE='/usr/share/feren-os/logos/Logo black.png'
OLDFILE='/usr/share/feren-os/logos/Logo white.png'
for filename in ~/.cinnamon/configs/zuromenu@feren/*.json; do
    for ((i=0; i<=0; i++)); do
        sed -i "s~$NEWFILE~$OLDFILE~g" "$filename"
    done
done

```

**Comment by feren** [comment]
@Elbullazul Hopefully you'll be able to fix this...

**Comment by Elbullazul** [comment]
@feren please open the bug in the Slingshot repo

**Comment by feren** [comment]
@Elbullazul 404 Issues Panel Not Found
Suggestions:
Enable It in Settings on the Repository

**Comment by feren** [comment]
@Elbullazul 
![capture2](https://cloud.githubusercontent.com/assets/11057934/25096286/8ebf83e4-2397-11e7-8ea3-3e020ccc1bc0.PNG)

**Comment by Elbullazul** [comment]
@feren try to clean up the panel before setting up the new order:

```shell
gsettings set org.cinnamon enabled-applets "['panel1:']"
```
I think this happens because Cinnamon tries to start a new instance of Slingshot before the current instance has finished running, hence a conflict between the 2 instances as to who will run. The current one wins, but is immediately destroyed by cinnamon and the 2nd isn't loaded, so that's why I think it fails

weird, didn't know one couldn't open issues on forks

**Comment by feren** [comment]
@Elbullazul It's in Settings > Tick Issues > Save

**Comment by feren** [comment]
@Elbullazul Sometimes though, this happens when beforehand, a different menu was used on the panel though, weirdly...

**Comment by Elbullazul** [comment]
so, did it work?

**Comment by feren** [comment]
Haven't tested it yet

**Comment by feren** [comment]
Ok, tried it with it being [] for 1 second, still having the bug, trying it with 5 Second Wait...

**Comment by feren** [comment]
Trying it with sleep 5 seems to have destroyed the issue, for now...

**Comment by Elbullazul** [comment]
@feren I added issues to slingshot repo, for next bug
