### ISSUE TITLE
Problem with panel indicators for xfce4-pulseaudio-plugin & xfce4-power-manager

### ISSUE THREAD

**Issue by imranmunshi** [B00merang-Project/Windows-10#89]
The panel indicators/widgets on the xfce4-panel for the above mentioned plugins look odd.
![screenshot_2017-04-18-12 14 26](https://cloud.githubusercontent.com/assets/5736192/25117725/dd8d5930-2430-11e7-9d56-35f6bb571f0a.png)

**Comment by Elbullazul** [comment]
@imranmunshi I don't have that on my system: 

![capture du 2017-04-18 07-51-49](https://cloud.githubusercontent.com/assets/15310985/25129425/02b55cb4-240c-11e7-8f26-5012bd6319f6.png)

are you using the master archive?

**Comment by imranmunshi** [comment]
@Elbullazul 
Yes, I am using the git version of the theme [Not the AUR version]. I have had this issue forever.

**Comment by Elbullazul** [comment]
which version of xfce4-panel do you have?

**Comment by imranmunshi** [comment]
4.12.1-1

**Comment by imranmunshi** [comment]
Bump

**Comment by Elbullazul** [comment]
I have 4.12.0 and can't go higher. Will have to wait till fedora updates to 26

**Comment by imranmunshi** [comment]
Has this issue been reproduced? I still have it with current Arch Linux and Windows-10 from git

**Comment by Elbullazul** [comment]
I haven't yet tried, but hopefully ubuntu 17.10 will have the problematic Xfce release

**Comment by Elbullazul** [comment]
fixed with [release 2.0](https://github.com/B00merang-Project/Windows-10/releases/tag/2.0)
