### ISSUE TITLE
No visual indicators for the presence of checkboxes and radio buttons

### ISSUE THREAD

**Issue by imranmunshi** [B00merang-Project/Windows-10#90]
![screenshot_2017-04-18-12 28 19](https://cloud.githubusercontent.com/assets/5736192/25118148/a2e2bd78-2432-11e7-98ca-a882431bf116.png)

**Comment by Elbullazul** [comment]
@imranmunshi it's probably an old version of the theme you're using

try [this version](https://github.com/B00merang-Project/Windows-10/archive/master.zip)

**Comment by imranmunshi** [comment]
@Elbullazul 
No effect. I am using the latest git master

**Comment by Elbullazul** [comment]
what version of gtk are you using?

**Comment by imranmunshi** [comment]
I am using the latest version from Arch repository.

**Comment by imranmunshi** [comment]
gtk2 2.24.31-1
gtk3 3.22.10-1

**Comment by imranmunshi** [comment]
Bump

**Comment by Elbullazul** [comment]
will need to remove some references, maybe today I can do this

**Comment by imranmunshi** [comment]
Any progress with this issue? I want to use this theme, but not having visual indicators for checkboxes and radios makes it a little harder

**Comment by Elbullazul** [comment]
@imranmunshi can you try the macOS theme and see if checkboxes load normally? I just issued a patch for a similar issue and may re-apply to this theme

link here: https://github.com/B00merang-Project/macOS-Sierra

**Comment by Elbullazul** [comment]
![bugfix](https://cloud.githubusercontent.com/assets/15310985/26692330/42d52e7a-46ce-11e7-8dd6-7acc9582a9df.png)

fixed (finally!)
