### ISSUE TITLE
KDE Is Not Recognised

### ISSUE THREAD

**Issue by opticyclic** [B00merang-Project/Windows-10#93]
When I run the installer I get 

    Identified Window manager. Waiting for association...
    We have been unable to associate your Desktop Environment. Executing Legacy Installation

I am running KDE on Ubuntu.

    $ plasmashell --version
    plasmashell 5.9.4

**Comment by Elbullazul** [comment]
@opticyclic at this moment we have no customization pack specifically designed for KDE. We used to have an aurorae theme but it broke on some machines, so we removed it.

maybe I should change that specific message to something less alarming
ex: KDE desktop detected. No extra material will be installed ?

**Comment by opticyclic** [comment]
That would help.
However, the README also specifies KDE and there is a Plasma5 directory in master (and the rolling branch) which makes it more confusing.

**Comment by Elbullazul** [comment]
@opticyclic it's a qtCurve file. I have no idea how to implement it from shell so I just put it there for manual install.

do you happen to know how to apply a qtcurve theme from the shell?

**Comment by cinnamoner** [comment]
(@Elbullazul Canould you attempt a W7 qtcurve for 5.9.5?)

**Comment by cinnamoner** [comment]
https://forum.kde.org/viewtopic.php?f=17&t=139667&p=374140&hilit=qtcurve#p374140

**Comment by cinnamoner** [comment]
https://forum.kde.org/viewtopic.php?f=309&t=132806&p=357185&hilit=qtcurve#p357185

**Comment by cinnamoner** [comment]
As much as I'd like qtcurve, it's not yet faisable.

**Comment by cinnamoner** [comment]
Unfortunately, nowadays, everything is flat. No more curves :( Desktop - Mobile convergence. Blah.

**Comment by cinnamoner** [comment]
As far as I know, there's no qtCurve support in Plasma 5.9.x. Currently, they are concentrating on other stuff.
