### ISSUE TITLE
menu entries all black

### ISSUE THREAD

**Issue by znbn** [B00merang-Project/Windows-10#95]
the foreground colour in application names, in the main manu, is black.
When I hover over it with the mouse, the background change in a lighter gray and the character is very bright and readable.
I use the theme with cinnamon. Should I change something in cinnamon/cinnamon.css ?

Jack

**Comment by Elbullazul** [comment]
@znbn can you post a screenshot?

**Comment by bluedxca93** [comment]
What version of cinnamon are you using?

**Comment by znbn** [comment]
I'm using Cinnamon 3.2 (see attached image)
![cinnamon-release](https://user-images.githubusercontent.com/1419422/26882260-2a664a9c-4b9a-11e7-8215-c95c50a4bb3b.png)

**Comment by Elbullazul** [comment]
are you using [this version?](https://github.com/B00merang-Project/Windows-10/archive/master.zip)

**Comment by znbn** [comment]
really, it was version Win 10 Light 0.9.9 SP1, not version 1.0.0.
Now I have installed your Windows 10 master and the problem has gone.
Just one more question: is it possible to hide the label Menu (see second screenshot).
![desktop](https://user-images.githubusercontent.com/1419422/26929438-04031f2c-4c5a-11e7-9af0-04796dd33a34.png)

**Comment by Elbullazul** [comment]
@znbn you right-click on the icon, select properties and delete 'menu' from the entry
