### ISSUE TITLE
selected text not highlighted properly while renaming a file.

### ISSUE THREAD

**Issue by znbn** [B00merang-Project/Windows-10#96]
when I press F2 to rename a file and then I select some characters, they are non highlighted properly.
Selected chars are just displayed in bold, but I can't see any different background.

I use cinnamon in Ubuntu 17.04.

Jack

**Comment by bluedxca93** [comment]
Not the theme  authors fault.
It is a known bug that can be fixed. Already in 16 4 that error on
both css and scss based themes. Which file manager are you using?.

**Comment by Elbullazul** [comment]
@znbn b728a06 should have fixed it. are you using the latest version?
