### ISSUE TITLE
Tooltips have no border, very less legibility

### ISSUE THREAD

**Issue by imranmunshi** [B00merang-Project/Windows-10#99]
The tooltips must have either a shadow or fill or border or strong gradient or something that would make them legible. Right now they are very much hard to notice. Look at the mouse pointer pointing at first pinned tab, there is a tooltip over there
![screen_2017-06-07-14 37 31](https://user-images.githubusercontent.com/5736192/26870910-1b7fdcce-4b8f-11e7-9136-5f15359d699c.png)

**Comment by Elbullazul** [comment]
@imranmunshi ok, will fix it soon too

**Comment by Elbullazul** [comment]
@imranmunshi we're working on a new GTK 3.20 version to fix a truckload of bugs that come with the current codebase. Will post update soon

**Comment by imranmunshi** [comment]
Hi @Elbullazul , no updaets for a long time?

**Comment by Elbullazul** [comment]
@imranmunshi having difficulties with maintenance, will shift work to a new source code structure for easier maintenance and scalability
